### ISSUE TITLE
how to autostart shariff secure on ubuntu (14.04)

### ISSUE THREAD

**Issue by cmdtstof** [heiseonline/shariff#103]
we try to add the command for the nodejs service into /etc/rc.locale without success.
but we also do not like to run the service as root.

what would be the best (secure) way to autostart shariff on ubuntu (best without init.d or systemd)?

thanks a lot

**Comment by compeak** [comment]
Have a look at [supervisord](http://supervisord.org/).

**Comment by cmdtstof** [comment]
thanks...
