### ISSUE TITLE
counter dosen't show up

### ISSUE THREAD

**Issue by Eltaris** [heiseonline/shariff#104]
Hello there!

I've installed the shariff backend and changed the domain in shariff.json into my domain. But the counter dosen't show up. 

![shariff](https://cloud.githubusercontent.com/assets/8537200/8969448/dbfd30ea-3643-11e5-8bfb-d1e4b59334f0.jpg)

I've tried to test the backend and this showed up.

![test](https://cloud.githubusercontent.com/assets/8537200/8969452/e6f7a0e8-3643-11e5-9657-97fd00b6c3e4.jpg)

Thanks for reading!
Remark: I am new to php and all other stuff.

**Comment by compeak** [comment]
This means your cache directory `/tmp` is not readable by shariff. Please have the `cacheDir` (see [cache settings](https://github.com/heiseonline/shariff-backend-php#cache-settings)) option point to a directory that is both readable and writable by shariff.

**Comment by Eltaris** [comment]
THANK you very much! Really! I've searched hours for the problem! Thanks!
