### ISSUE TITLE
Adding an Id to each button

### ISSUE THREAD

**Issue by manuxi** [heiseonline/shariff#105]
Is it possible (with little effort) to add ids to the generated buttons without modifying the sorce code?

**Comment by craiq** [comment]
as shariff buttons can be on your page more then once, there can't be static id's for each service.
for what do you need it?

**Comment by manuxi** [comment]
Yes, when using it more then once it makes no sense.
Our Online-Marketing-Team wants it for Google Tagmanager...

**Comment by craiq** [comment]
When you are sure, it's just used once, you can make an easy change and compile it yourself.
shariff.js Line 196
var $li = $('<li class="shariff-button">').addClass(service.name);
to
var $li = $('<li class="shariff-button">').addClass(service.name).attr('id', service.name);

**Comment by manuxi** [comment]
Thank you for your answer.
We did this at first approach but decided to externalize it to avoid issues with a new version:

$(document).ready(function() {
   $('.shariff .shariff-button').each(function(){
      var serviceName = /\s+(.*)/.exec($(this).attr('class'))[1];
      $(this).children().each(function(){
         if ($(this).is('a')) {
            $(this).attr('id', 'sharebutton' +serviceName);
            return false;
         }
      });
   });
});

**Comment by compeak** [comment]
Closing this since there has been no further activity.
