### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by craiq** [heiseonline/shariff#106]
Just checked Browser Support for IE
Down to IE 9 it is working, but IE 8 isn't

There are some easy fixes for forEach and hasOwnProperty, but it comes to url module that just support IE 9+

Also the Flex-box from CSS is just supported IE 10+ http://caniuse.com/#search=flex

Do you want to support IE8 too, whats still common or drop support for this?
(You closed the question for svg icons because of browser support)

Should also be written in Readme

**Comment by compeak** [comment]
Linking the SVG question: #46 

We are thinking about this.

**Comment by GustavR** [comment]
As a temporary fix (not tested completely) following worked for me (put in separate JS source file above `shariff.complete.js`):
```javascript
HTMLDivElement.prototype.hasOwnProperty = HTMLDivElement.prototype.hasOwnProperty || Object.prototype.hasOwnProperty;

if (typeof Array.prototype.forEach != 'function') {
    Array.prototype.forEach = function(callback){
      for (var i = 0; i < this.length; i++){
        callback.apply(this, [this[i], i, this]);
      }
    };
}

if(typeof String.prototype.trim !== 'function') {
  String.prototype.trim = function() {
    return this.replace(/^\s+|\s+$/g, ''); 
  }
}

if (!Object.keys) {
  Object.keys = function(obj) {
    var keys = [];

    for (var i in obj) {
      if (obj.hasOwnProperty(i)) {
        keys.push(i);
      }
    }

    return keys;
  };
}
```

**Comment by craiq** [comment]
great this works well!

foreach and hasOwnProperty is easy to fix in shariff.js
the other both I insert before the url modul call and everything works as it should

**Comment by craiq** [comment]
here is my version, working in IE 8 and now with a circular theme :)
https://craiq.github.io/shariff/

**Comment by compeak** [comment]
We decided to support the last two major releases of Firefox, Google Chrome, Internet Explorer/Edge and Safari.

This means
- Firefox 43/42
- Google Chrome 48/47
- Edge 25/ Internet Explorer 11
- Safari 9/8
