### ISSUE TITLE
default curl connection timeout of 150 seconds in guzzlehttp is to high

### ISSUE THREAD

**Issue by ndorphin** [heiseonline/shariff#107]
Hi,

the default curl connection timeout of 150 seconds in GuzzleHttp\Ring\Client\CurlFactory is ways to high. It seems that in some configurations the curl requests could run into this timeout. In that case your php script is running the whole 150 seconds (or breaks before if you have limited the script time). On high traffic website this may result in running out of free php (fpm) processes. Happens here :(
I guess the reason is that the curl request to read the number of shares could be blocked (or just being unanswerd) by some social media services if you reach a defined limit. Because i don't have the request urls i can't debug wich service is the problem. Here only 1+, facebook and twitter are used, it must be one of them.
I strongly recommend to change the 150 seconds default to a lower value, 5 seconds should be enough in my mind.

best
jan

**Comment by compeak** [comment]
Setting the `timeout`-option [here](https://github.com/heiseonline/shariff-backend-php/blob/master/src/Backend/Request.php#L37) should work. I'm looking into this.
