### ISSUE TITLE
sharing facebook on mobilephone doesn't work

### ISSUE THREAD

**Issue by leibler** [heiseonline/shariff#109]
after clicking the f (facebook) share button on mobilephone the normal sharing window comes up (everything works fine). 
but after clicking "share" there comes an error message (see attached screenshot).
![facebook_shariff_share_on_mobilephone_11880176_10205332839504934_988261294_n](https://cloud.githubusercontent.com/assets/4221541/9276883/e4abc0ca-42a6-11e5-9632-ad49684bebf5.jpg)

**Comment by Wootime** [comment]
Nach meinem Test ist dieser Fehler behoben. Wenn man jedoch die Facebook App auf dem iPhone installiert hat, wird diese leider nicht geöffnet. Stattdessen wird Facebook über den Browser geöffnet. Evtl. könnte man hier ja eine weitere Bedingung hinzufügen, die das Öffnen in direkt in der App erlaubt. Im Fall von Pinterest wird hier auch direkt die App angesprochen (wenn sie installiert ist) auch wenn es aktuell leider nicht funktioniert.
