### ISSUE TITLE
Shariff does not work with WP Theme Materialist

### ISSUE THREAD

**Issue by cwordpress** [heiseonline/shariff#111]
Hi,

I use the theme Materialist (http://fikrirasy.id/portfolio/materialist/) on WP. I have installed Shariff, but the icons are not displayed. Neither on the bottom of a blog post nor as widget in the menu (left hand side, bottom "Social")

http://dampffreiheit.ch-lippmann.de

Do you have any idea why?

Kind regards,
Christian

PS. if I use another theme like New Dark, it works fine.

**Comment by sehkunde** [comment]
Hi,

jQuery is loaded after shariff.js and two other scripts which depend on it. You can see the errors using the console from your browsers Dev Tools/Web Inspector.
Shariff must load after this line:

    <script type="text/javascript" defer src="http://ch-lippmann.de/blog/dampffreiheit/wp-content/cache/autoptimize/js/autoptimize_218932a621a123458930b1c6bb95486e.js"></script>

and it may be necessary to drop the defer (or add it to shariff.js as well).

**Comment by cwordpress** [comment]
Hi,
this path "/cache/autotimize/" bringing me to check the installed plug-ins. I found the Plug-In "Autoptimize". So I deactivate the Plug-In and now Shariff-Wrapper works as before again!

The interesting is, that the plug-in is installed a long time ago and with another theme there were no issues.

But anyway => now I'am happy that it is working again!

Thanks for your quick support!
