### ISSUE TITLE
Option to set captions and target URLs for buttons

### ISSUE THREAD

**Issue by pmamat** [heiseonline/shariff#112]
Hello everybody,

First of all: I really like Sharrif from the point of view of privacy and the very cool design. I really appreciate the idea of a "one click" solution.

I would be extremly happy to be able to simply strip the "one click" functionality and reduce it to just the privacy functionality (esp. getting the number of facebook likes and twitter followers). I just would like to link the facebook page (with the timeline) and the twitter profile.

It would be great if you could give the options to set the legend on the button (e.g. just "Facebook" / "Twitter") and the link target URLs (e.g. www.facebook.com/xyz). Then every user could decide how thoroughly (s)he would like to use this great tool!

Looking forward to hearing further ideas and comments on this topic!
Regards,
 Philipp

**Comment by compeak** [comment]
This would change the expected behaviour of the buttons. To prevent confusion we would need a new kind of button (e.g. displaying some sort of symbol). This sounds more like a new project than shariff.
