### ISSUE TITLE
script creates invalid html by using popup for rel-attribute

### ISSUE THREAD

**Issue by moellerbj** [heiseonline/shariff#113]
This part was created:

> a href="https://www.facebook.com/sharer/sharer.php?u=webpage" rel="popup" title="Bei Facebook  teilen" role="button" aria-label="Bei Facebook teilen"><span class="fa fa-facebook"></span><span><class="share_text">teilen</span></a

The w3 validator shows:
> Bad value popup for attribute rel on element a: The string popup is not a registered keyword.

Better way is to use data-rel="popup"

**Comment by ipa01** [comment]
Thanks - I just fixed this. It will be available with the next release.
