### ISSUE TITLE
tag v1.16.0 is still v1.15.0

### ISSUE THREAD

**Issue by Amomo** [heiseonline/shariff#114]
Hi, I found that files in v1.16.0 are still in an old version.
Though we could get it from master branch now, I think to get v1.16.0 from a right version number would be better.
Would you consider to modify it? Thank you~ :-D

**Comment by compeak** [comment]
This should be fixed as of [1.17.1](https://github.com/heiseonline/shariff/releases/tag/v1.17.1).
