### ISSUE TITLE
Possibility to add a callback function.

### ISSUE THREAD

**Issue by eimsbushsouth** [heiseonline/shariff#115]
I would like to have the possibility to inject a callback into the click-action which could be solved by adding another option.

``` javascript
new Shariff(buttonsContainer, {
    orientation: 'vertical',
    callback: function(service) {
        // To some other stuff, eg. track where and what the user wants to share.    
},
});
```

May be like this?

``` javascript
        // event delegation
        $buttonList.on('click', '[rel="popup"]', function(e) {
            e.preventDefault();

            var url = $(this).attr('href');
            var windowName = '_blank';
            var windowSizeX = '600';
            var windowSizeY = '460';
            var windowSize = 'width=' + windowSizeX + ',height=' + windowSizeY;

            global.window.open(url, windowName, windowSize);
            if(service.callback !== undefined && is_function(service.callback) {
                service.callback(service);
            }

        });
```

**Comment by craiq** [comment]
isnt it easier to add your own code after the shariff.js?
its just this:

$('.shariff').on('click', 'a', function() {
	"use strict";
	var sm = $(this).closest('li').attr('class').replace('shariff-button ', '');
	console.log(sm);
});

**Comment by flixx** [comment]
It would be good, if the callback function get triggered on a successful share.
( I want to track successful shares with Google Analytics Events )

**Comment by compeak** [comment]
It looks like the better solution would be custom events. A pull request would be very welcome.

**Comment by compeak** [comment]
Superceded by #160.
