### ISSUE TITLE
Whats App sharing

### ISSUE THREAD

**Issue by mkra** [heiseonline/shariff#119]
Whats App sharing is only possible on iPhone so it would make sense to hide the button on all other devices (including desktop).

**Comment by derChristoph** [comment]
this woud be nice, with an Bootstrap class="hidden-xs" for example?

**Comment by compeak** [comment]
> Whats App sharing is only possible on iPhone

How did you get that impression?

**Comment by mkra** [comment]
It did not work in my implementation, but it was another bug i noticed. So it only does not work on desktop and needs to be disabled there.

**Comment by compeak** [comment]
We decided not to change the current behaviour because there is a WhatsApp web client. Using something like [Google Chrome's handlers](https://support.google.com/chrome/answer/1382847?hl=en) could make the button work in desktop browsers at a later time.
