### ISSUE TITLE
NoFollow Attribut

### ISSUE THREAD

**Issue by Wootime** [heiseonline/shariff#124]
Aktuell fehlt leider das nofollow Attribut an jedem Link. Das bedeutet das jeder Sharing-Link als externer Link gezählt wird. Das ist für SEO natürlich sehr negativ.

Könnt ihr dieses Attribut bitte noch optional einfügen?

Man könnte es durch das hinzufügen von "n.attr("rel", "nofollow")" lösen. Dann funktioniert jedoch nicht mehr das PopUp. Hat jemand eine bessere Idee?

**Comment by MathiasWeisheit** [comment]
Wenn meine Änderungen eingearbeitet würden, könnten Sie ihre Links und Schaltflächen selbst gestalten.

**Comment by craiq** [comment]
@MathiasWeisheit 
1. Nein deine Änderungen reichen dafür nicht aus
2. Es ist schon dreist 6min später von einem Freund drunter schreiben zu lassen, dass der Code doch bitte eingepflegt werden soll (ja die Zeit hab ich mir gemerkt, bei der Dreistigkeit)
3. Es fehlt immer noch eine Umsetzung für die Zähler
4. Setzt sich keiner ran und schreibt deinen Code nach. Wenn solltest du einen ordentlichen Pullrequest machen. Und selbst dann heißt das noch lange nicht, dass dein Code auch übernommen wird

 @Wootime dafür musst du in der ganzen shariff.js die Zuordnung von rel zu einem neuen Attribut ersetzen. Also auch in den on click handlern.
Hab das ganze mal in meinem Build gemacht: https://github.com/craiq/shariff/
Der ist aber deutlich umfangreicher, als das Original. Du kannst aber durch anpassen der config.json dir den kleinst nötigen Build erzeugen. Einfach mal die Readme durchschauen.

Ein Kreis-Theme gibt es da auch ;)

**Comment by MathiasWeisheit** [comment]
@craiq:
1. ok
2. Ich kenne @ andrelohmann  nicht
3. ich weiß
4. Ich habe nur versucht, einen Ansatzpunkt für eine Erweiterung zu liefern. Ich kenn mich in dem Projekt nicht aus und will mich nicht zu tief einmischen. Deshalb habe ich auch nur meinen Vorschlag geliefert.
@craiq : Wenn ich Sie/Dich damit verärgert haben sollte, tut mir das leid!

**Comment by compeak** [comment]
> Das ist für SEO natürlich sehr negativ.

Das ist zu pauschal.

[Hier](http://webmasters.stackexchange.com/questions/72059/nofollow-on-share-links) und ausfuehrlicher [hier](https://support.google.com/webmasters/answer/96569?hl=en) kann man nachlesen, dass es prinzipiell drei Gruende gibt, ```nofollow``` zu setzen:

- man vertraut den Links nicht (z.B. Link-Spam)
- es sind bezahlte Links
- Priorisierung des Crawlers

Auf Shariffs share-Links trifft keine der Kategorien zu.
