### ISSUE TITLE
Sharing Pinterest-Link funktioniert unter iPhone nicht

### ISSUE THREAD

**Issue by Wootime** [heiseonline/shariff#126]
Beim Klick auf den Pinterest-Button erhält man in der installierten App die Fehlermeldung "Fehler - Pin nicht gefunden). Über den Browser am Desktop funktioniert es problemlos. Ich nehme an das der Fehler daraus resultiert, wenn die App installiert ist und diese dann statt dem Browser geöffnet wird.

**Comment by craiq** [comment]
Shariff gibt nur einen Link aus, da kann man nichts dran ändern.
Der Fehler liegt bei iOS.

**Comment by compeak** [comment]
> Der Fehler liegt bei iOS.

Sehe ich genauso.
