### ISSUE TITLE
Update with new Facebook and Google Plus Logos?

### ISSUE THREAD

**Issue by SinnlosS** [heiseonline/shariff#127]
Hi there,

really nice plugin, we're using it on our website. It would be great if you could update the facebook and google plus logos, as those have changed.

Best regards
SinnlosS

**Comment by moortaube** [comment]
Hi there, too!

Logos came from [Font Awesome](https://github.com/FortAwesome/Font-Awesome/), so your issue should be placed there. :)

Best regards
moortaube
