### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by craiq** [heiseonline/shariff#130]
Hi all,

In my [build](https://github.com/craiq/shariff) I've implemented a lot new things.
Here is a overview:
* IE8 compatibility
* more accessibility improvements (e.g. for keyboard user)
* translations are separated to easy modify for own needs and not bloat the files for all
* more servies
* new CSS (in my eyes more compatible and flexible and most important it don't rely on media queries)
* services CSS is generated in a loop with variables from a json file (much faster and easier to edit)
* config file that will allow to compile much smaller needed files with cutting out unwanted services and few more useful options
* button to show more services
* circle themes [Demo](http://craiq.github.io/shariff/)

Are some of those features wanted? When yes I can make pull requests for them

**Comment by florianfink** [comment]
improved accessibility and compatibility is always wanted, in my opinion. the circle themes look great as well!

**Comment by compeak** [comment]
New services are always welcome (One pull request per service, please.). We are thinking about your offered changes.

**Comment by craiq** [comment]
do you also want:
* facebooklike (need tooltip in shariff.js)
* googleplusplus (need tooltip in shariff.js)
* print (need print in shariff.js)
* more (need more in shariff.js)

**Comment by compeak** [comment]
I just merged #133 (reddit), #134 (stumbleupon), #135 (threema).

**Comment by devtype** [comment]
Would you also consider adding print to the services. It seems like a good addition.

**Comment by compeak** [comment]
@devtype: I don't really like putting service-specific code into ```shariff.js```. What about a button that takes the pregenerated URL of the print version of the current page as a ```data-``` attribute and links to it?

**Comment by craiq** [comment]
@compeak
Another solution came to my mind
Add a click option to the services. When it's set, then shariff.js will run it onclick on this service button. The print service won't have a URL option and just the click option. This option then has the print command.

**Comment by compeak** [comment]
> Add a click option to the services. When it's set, then shariff.js will run it onclick on this service button. The print service won't have a URL option and just the click option. This option then has the print command.

This adds complexity. Why should this be implemented instead of a ```data-``` attribute?

**Comment by ikkez** [comment]
please add a print button

**Comment by compeak** [comment]
We have decided against implementing the suggested solutions, but a  pull request introducing a print button using `window.print` would be welcome.
