### ISSUE TITLE
Facebook HashTag Unterstützung

### ISSUE THREAD

**Issue by jschmahl** [heiseonline/shariff#132]
Die HashTag -Funktionalität von Facebook ist mittlerweile nur über die API Benutzung möglich.
Sollte ein HashTag an der URL vorhanden sein, wird dieser von Facebook ignoriert.

**Comment by compeak** [comment]
Meinst du einen tatsächlichen Hashtag im Sinne von Twitter oder den [Fragment-Teil](https://en.wikipedia.org/wiki/Uniform_Resource_Locator#Syntax) von URLs?

**Comment by jschmahl** [comment]
Ich meine das URL Fragment welches man in der aktuellen Facebook API separat auslesen und verwenden kann.

Bsp: http://example.de/aktuelles#ArtikelUeberschrift

**Comment by compeak** [comment]
Wo genau siehst du jetzt ein Problem in Shariff, bzw. was würdest du ändern?

**Comment by jschmahl** [comment]
Wie man das Ändern kann weiß ich leider nicht. Bin auch leider nicht firm bzgl. der Social Media APIs.
Ich wollte es lediglich anmerken das die Möglichkeit über die sharer.php nicht die Nutzbarkeit der HashTag-Funktion einschließt.
Ein Problem gibt es hierbei nicht es sollte lediglich eine Anmerkung des Funktionsumfangs darstellen. Eventuell haben da ein paar schlaue Köpfe eine Idee wie man die Integration möglich machen kann, denn Shariff finde ich eine klasse Lösung zur Social Media Integration auf Webseiten.

**Comment by compeak** [comment]
Ich schließe das erstmal. Falls jemand eine Idee hat, kann das Ticket gerne wieder geöffnet werden.
