### ISSUE TITLE
Hide mobile services when not usable

### ISSUE THREAD

**Issue by Guite** [heiseonline/shariff#136]
Would it be possible to hide (at least) whatsapp and threema when they can not be used by the client's browser? The benefit would be avoiding an error message like thrown by Firefox on desktop machines if you click on these buttons.

As a workaround I sometimes do a mobile device detection and show the buttons only if a mobile device has been detected.

**Comment by craiq** [comment]
Should be possible by checking the platform.
```var platform = navigator.platform;```
If its Android or iOS it will be shown

**Comment by compeak** [comment]
I'm not sure whether we want this. Some browsers support custom protcol handlers (e.g. `itunes://` or `steam://`). Something like `whatsapp://` could work on desktop systems.

**Comment by compeak** [comment]
> when they can not be used by the client's browser?

There is no way to detect this.

A simple mobile device detection would be
a) not good enough (see my previous comment)
b) out of scope of this project.

If you need to hide certain buttons in specific situations, you will have to provide some kind of wrapper of your own origin (see the second example [here](https://github.com/heiseonline/shariff#getting-started-using-npm)).
