### ISSUE TITLE
No Twitter Share-Counts

### ISSUE THREAD

**Issue by Tinendo** [heiseonline/shariff#140]
The Twitter Share-Counts disappeared overnight. It seems to be an general error/issue.

Even the original Heise article (http://www.heise.de/newsticker/meldung/Datenschutz-und-Social-Media-Der-c-t-Shariff-ist-im-Einsatz-2470103.html) is affected. So I assume that this might be an API-Change by Twitter itself (?).

**Comment by compeak** [comment]
Twitter disabled their share count api. See [this issue](https://github.com/heiseonline/shariff-backend-php/issues/46). Closing as invalid because this is a backend issue.
