### ISSUE TITLE
default mail body option "<URL>" is not visible on iphone

### ISSUE THREAD

**Issue by backbone87** [heiseonline/shariff#141]
see https://github.com/hofff/contao-shariff/issues/11 (german)
default option: https://github.com/heiseonline/shariff/blob/master/src/js/shariff.js#L89

**Comment by tilmanjusten** [comment]
You may override the default mailBody method with your own:

```js
Shariff.prototype.defaults.mailBody = function() { return window.location.href; };
new Shariff($('.shariff'));
```

**Comment by backbone87** [comment]
@tilmanjusten i know i can override the mail text, but that isnt the point. lot of ppl use apple mail and if there is no URL in the mail template the share via mail function is basically useless with apple mail as the sender.

**Comment by compeak** [comment]
A pull request fixing this bug would be welcome.

**Comment by backbone87** [comment]
https://github.com/heiseonline/shariff/blob/master/src/js/shariff.js#L92

<URL> gets removed by apple mail
`mailBody: function() { return '<' + this.getURL() + '>'; },`

URL will not be removed by apple mail
`mailBody: function() { return this.getURL(); },`
