### ISSUE TITLE
data-title only used as a fallback

### ISSUE THREAD

**Issue by Klopfer1402** [heiseonline/shariff#143]
This issue was also raised in #43, but obviously it still persists: The data-title attribute is only used if there's no DC.title meta tag. This is backwards logic: If I have multiple blog posts on one website, I'd like Shariff to use the individual data-title attributes instead of the title for the blog as a whole.

Instead of checking the length of DC.title and then falling back on getTitle() if DC.title.length is 0, it should check the length of the return value of getTitle() first and use that if it's there, right?

**Comment by liayn** [comment]
Sounds very reasonable.

**Comment by compeak** [comment]
A pull request fixing this bug would be welcome.
