### ISSUE TITLE
Mehr als eine Domain

### ISSUE THREAD

**Issue by frankthies** [heiseonline/shariff#145]
Hallo,

shariff ist wirklich ein sehr gutes Tool und ich würde es gern in einem Projekt nutzen, in welchem über ein CMS verschiedene Websites mit unterschiedlichen Domains verwaltet werden. Bisher habe ich keine Möglichkeit gefunden, wie man in der shariff.json mehrere Domains angeben kann. Für jede einzelne Domain ein separates shariff einzurichten, treibt den Aufwand bei Updates aber sehr nach oben.

Gibt es denn die Möglichkeit mehere Domains mit einer shariff-Installation zu nutzen resp. wenn nicht, könnte das nicht in das Script mit eingearbeitet werden?

Danke im Voraus / VG

Frank-André Thies

**Comment by 3UU** [comment]
Aehm, wieso geht das nicht? Du muesst doch die Domain nirgends konfigurieren. Die "shariff.json" gehoert zum Backend. Da waerst Du uebrigens eher https://github.com/heiseonline/shariff-backend-php richtig ;-) Du kannst auch dort die Domain dynamisch reinschreiben, wenn Du Deinen Webserver so konfigurierst, dass er diese auch von PHP parsen laesst. Aber auch eher doof, denn bei jedem Update musst Du dran denken, es neu einzupflegen. Also lieber einen externen Backend-Server eintragen. Du kannst Dir als backend aber auch einfach eine Installation von Wordpress mit dem Plugin https://de.wordpress.org/plugins/shariff/ bauen. Da musst Du dann nur fuer jeden neuen Server, der es nutzen soll, die Domain ins Array SHARIFF_FRONTENDS packen.

So, genug OT ;-)

**Comment by liayn** [comment]
@frankthies: Benenne vielleicht dein CMS, dann kann der jeweilige Extension Autor besser behilflich sein, sofern er hier mitliest. Aber wie @3UU schon geschrieben hat, vermutlich bezieht sich die Problemstellung eher auf das shariff backend, dort wirst du auch eher dann die Ext Autoren antreffen.

**Comment by frankthies** [comment]
Hallo und Danke für Eure Antworten.

Ihr habt natürlich vollkommen recht, meine Frage betrifft das backend und ist daher hier fehl adressiert. Sorry :(

Das CMS ist ein eigenentwickeltes und daher kann ich nicht auf fertige Scripts zurückgreifen.

Schönen 4. Advent noch!
