### ISSUE TITLE
Blocked loading mixed active content ...shariff

### ISSUE THREAD

**Issue by Gitjk** [heiseonline/shariff#148]
I'm not sure if this is the correct place, because I'm using the 'shariff for Joomla plugin'.

There is a problem when the page is accessible via http and https. Important parts of our pages are not loaded when accessed via https and Firebug shows these error messages:

Blocked loading mixed active content "http://mydomain.com/media/plg_jooag_shariff/css/shariff.min.css"
Blocked loading mixed active content "http://mydomain.com/media/plg_jooag_shariff/js/shariff.min.js"

As far as I can see the problem is that shariff writes the absolute http url into the Joomla cache. I suppose the blocking would not happen if relative urls would be used.

**Comment by compeak** [comment]
Closing because [this](https://github.com/joomla-agency/plg_jooag_shariff/issues/19) is the correct place.
