### ISSUE TITLE
provide diaspora as an option

### ISSUE THREAD

**Issue by markum** [heiseonline/shariff#15]
Would be nice to have a "share on diaspora" option too. I know they are not compromising privacy, but it is a kind of shame that they are missing because of this. On first klick the the user would provide his pod-address which then would be stored locally.

**Comment by compeak** [comment]
We will not implement this ourselves, but pull requests are welcome. Please keep in mind that the Diaspora logo **must not** be included (not even in your git history).

**Comment by Flaburgan** [comment]
@compeak we can of course give you the authorization to use the logo if the project keeps the spirit of diaspora* :)

**Comment by annando** [comment]
One could use the data from this plugin: http://sharetodiaspora.github.io/about/

**Comment by craiq** [comment]
added: - it's next to the tumblr button
http://craiq.github.io/shariff/
logo is what fits best from font awesome
I used http://sharetodiaspora.github.io/about/ - very easy to include with this

**Comment by annando** [comment]
Thanks a lot!

**Comment by annando** [comment]
@craiq Could you make a pull request?

**Comment by craiq** [comment]
@annando done :)

**Comment by compeak** [comment]
@craiq Your pull request (#129) has been merged. Thank you for your contribution.
