### ISSUE TITLE
shariff.complete.css -  privacy 

### ISSUE THREAD

**Issue by mafranke** [heiseonline/shariff#154]
Shariff target is to aware the privacy for the user:
The shariff.complete.css is linking to font awesome on a cdn. (https://netdna.bootstrapcdn.com)

@heise is that link allowed in germany, with no information about the privacy terms on your website? You direct the user to a us company without his knowledge?

The TMG and BDSG is a madness :(

**Comment by compeak** [comment]
We see your problem with the current solution. The only reason behind it was to make [the demo site](http://heiseonline.github.io/shariff/) work on GitHub pages. Currently we are thinking about replacing font awesome with vector icons.

**Comment by scheinercc** [comment]
> replacing font awesome with vector icons

Has this happened yet?

**Comment by compeak** [comment]
@scheinercc: No. So far there has been no progress on this issue.

**Comment by compeak** [comment]
This has been fixed in the more recent releases. Shariff doesn't load anything from third parties anymore.
