### ISSUE TITLE
Fatal error: Class not found

### ISSUE THREAD

**Issue by DrupalFabe** [heiseonline/shariff#157]
After installing my backend the test just returns:

<br /><b>Fatal error</b>:  Class 'Heise\Shariff\Backend' not found in <b>/www/htdocs/w0117e00/kunst-in-bildern/shariff-backend-php/index.php</b> on line <b>27</b><br />

Test URL: http://www.kunst-in-bildern.de/shariff-backend-php/?url=http%3A%2F%2Fwww.kunst-in-bildern.de

Is there any clue where this error is coming from?
Thanks for Feedback
Fabian

**Comment by liayn** [comment]
Looks like this is a drupal page. Maybe try the drupal module as linked in the readme.
https://github.com/heiseonline/shariff#third-party-integrations

**Comment by liayn** [comment]
Other than that this is the wrong project -> head over to https://github.com/heiseonline/shariff-backend-php/ for shariff-backend related issues.

**Comment by compeak** [comment]
> Other than that this is the wrong project -> head over to https://github.com/heiseonline/shariff-backend-php/ for shariff-backend related issues.

Exactly.
