### ISSUE TITLE
provide a local like option

### ISSUE THREAD

**Issue by markum** [heiseonline/shariff#16]
It would be good to have local like option, like it is provided by the plugin "https://wordpress.org/plugins/wp-likes/" (which is not developed anymore). A local like option would also be in the sense of keeping privacy. Having it here in the plugin in the same design would make it easiert and more appealing for bloggers to implement it.

**Comment by compeak** [comment]
Adding a component that requires persistent storage would break with shariff only being a proxy.

If you need a local like option, I would recommend implementing it yourself and adding it as a share-service to shariff.
