### ISSUE TITLE
Prepare for (piwik-) tracking of usage of shariff - for quality ensurance and optimization

### ISSUE THREAD

**Issue by hpvd** [heiseonline/shariff#160]
Doing some tracking of shariff's sharing process on ones website would help to
**1) optimize shariff / it's setup**
- **remove share buttons** which are never used by users or
- **make them better visible/accessible** to the user
  (on different types of sites (category, detail, ..) on the website)

**2) make quality insurance regarding browser compatibility**
e.g. firefox users
- never share anything,
- never share via fb 
- always do page reload after sharing
- etc

If there are findings regarding shariff itself, website owner can open an issue here on github, one can fix it and **shariff becomes better and better :-)**
If there is no / no easy tracking, the chance for and number of problem reports would be much lower...

All this could be easily done with tracking software having the possibility to track more than only site visits...

Since Piwik is a wide spread OS software and has the needed feature (event tracking)
it would be very handy to **prepare shariff to have tracking features ready for deployment** out of the box.

**Comment by hpvd** [comment]
In general event tracking is done in Piwik this way

e.g. via js:

_paq.push(['trackEvent', 'category', 'action', 'name', value]);


for details see:
https://piwik.org/docs/event-tracking/

**Comment by hpvd** [comment]
in Piwik it would looks like this in "visitor log"-view
![2016-04-26_14h36_46](https://cloud.githubusercontent.com/assets/5681880/14818336/d76395ca-0bbc-11e6-80dd-085b26aff1af.png)

plus: statistics of "how often which action" etc.
for an example see here:
https://demo-anonymous.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?module=Events&action=index&idSite=1&period=year&date=today

Both views could be filtered by browser, browser version etc
Filter setup looks like this:
![2016-04-20_14h08_00](https://cloud.githubusercontent.com/assets/5681880/14673963/544c994e-0701-11e6-80f3-8036fd69f627.png)

**Comment by hpvd** [comment]
In a second step one could maybe also provide the numbers:

_paq.push(['trackEvent', 'shariff', 'sharing', 'twitter', 136]);

![2016-04-26_14h44_56](https://cloud.githubusercontent.com/assets/5681880/14818471/ae8e661a-0bbd-11e6-86db-fe44fb2d17b9.png)

**Comment by hpvd** [comment]
of course a feature like this should have a setting for enable/disable it...

**Comment by hpvd** [comment]
if this is available it could be listed here:
https://piwik.org/integrate/

nice side effect: this would give shariff another chance to be find by even more users + a backlink :-)

**Comment by compeak** [comment]
A pull request introducing custom events would be accepted (see #151 and #115 ). We will not implement some kind of tracking interface, since that would rather belong in your sites code.

**Comment by znerol** [comment]
PR here #266
