### ISSUE TITLE
Ajax request issue

### ISSUE THREAD

**Issue by vs-rm** [heiseonline/shariff#164]
Hey guys,
i hope anyone could help me. I integrated the shariff functionality in OXID by creating a module which add the container on the product detail page.
But in case the product is an variant, there are ajax request when chosing one.
After the call the social media icons disappear.

Is there a way, calling shariff function again, after ajaxSuccess?
I'm not so experienced in JavaScript so maybe someone has a solution, how to fix my problem?

**Comment by fabtho** [comment]
I have the same problem. Solution:

just call this funtion after ajaxSucess

```
$('.shariff').each(function() {
    if (!this.hasOwnProperty('shariff')) {
        this.shariff = new Shariff(this);
    }
});
```

(after loading shariff.min.js). This is the same function called at the ende of https://github.com/heiseonline/shariff/blob/master/src/js/shariff.js
