### ISSUE TITLE
Whatsapp Button always displayed (no difference desktop/mobile)

### ISSUE THREAD

**Issue by sab1989** [heiseonline/shariff#168]
Maybe someone can help. Installed shariff ordinarily with .js and .css put where the install guide says. Buttons are showing up - so far so good. My issue is that I want the whatsapp button to show only on mobile devices but it shows up on desktop as well. 

Can you tell me if there is another config where there is an option for it? 
Or should it work from the beginning with the js and css file installed?
Or do I have to install via npm?

Thanks in advance for help!

**Comment by creatoras** [comment]
The original makes no difference between desktop and mobile. You have to customize it.

**Comment by sab1989** [comment]
Ok, I thought it would be a standard feature. 
Is there a more elegant way to customize it the way I want than to just hide it via CSS?

**Comment by craiq** [comment]
`@media (max-width:550px) {  .shariff .whatsapp {  display: none;  } }`

Insert a max-width you think fits for mobile, but 550px should be fine. Problem are tablets with whatsapp.

**Comment by sab1989** [comment]
Thank you very much, that helped a lot :)
