### ISSUE TITLE
Flexbox bug on horizontal orientation Safari

### ISSUE THREAD

**Issue by yellowled** [heiseonline/shariff#169]
Reproduceable in current Safari (Safari 9.1.1, iOS Safari 9.3.2), see second example on http://heiseonline.github.io/shariff/.

Screenshot:
![screenshot 2016-06-21 16 27 29](https://cloud.githubusercontent.com/assets/326223/16233007/1d8931ae-37cd-11e6-81c7-f163bf101643.png)

Fix: Replace `flex: 1;` [in shariff-layout.less](https://github.com/heiseonline/shariff/blob/master/src/style/shariff-layout.less#L150) with `flex: 1 0 auto;`. (I guess you are using autoprefixer for the vendor prefixes?)

**Comment by ipa01** [comment]
Your fix is added and will be active with the next version - thanks
