### ISSUE TITLE
list of all supported social sharing possibilities

### ISSUE THREAD

**Issue by hpvd** [heiseonline/shariff#173]
Would be nice to see a list of all supported social sharing possibilities on main site
https://github.com/heiseonline/shariff

**Comment by liayn** [comment]
See https://github.com/heiseonline/shariff#options-data-attributes

**Comment by hpvd** [comment]
ah thanks,

just looked into first 3-4 rows of table. Got the impression there are only details inside one would need later for detailed config.
=> Maybe this should be a little more prominent with an own headline + maybe also the belonging icons..
