### ISSUE TITLE
Privacy policy template?

### ISSUE THREAD

**Issue by stefahn** [heiseonline/shariff#176]
Is there a (German) template for the privacy policy (Datenschutzerklärung) ?

I found that heise doesn't mention Shariff in their [privacy policy](http://www.heise.de/Privacy-Policy-der-Heise-Medien-GmbH-Co-KG-4860.html). Other sites like [tk.de](https://www.tk.de/tk/datenschutz-und-informationsfreiheit/datenschutz/datenschutzerklaerung/93066) or [this one](https://stiftungdatenschutz.org/datenschutzerklaerung/) seem to have their own text. 

Having a template would make things easier for webmasters. In my eyes this would lead more webmasters to use Shariff.

**Comment by compeak** [comment]
We do not provide a template for privacy policies.

**Comment by richard67** [comment]
This is what the info link should be used for, link to your own privacy policy on your web site.
