### ISSUE TITLE
Problem mit metadaten beim Teilen auf Facebook

### ISSUE THREAD

**Issue by Mausbiber** [heiseonline/shariff#181]
Hallo,

ich arbeite gerade an einer neuen Version einer Homepage und nutze auf dieser auch SocialMedia Buttons.

Damit das Ganze datenschutzkonform ist, nutze ich die von heise.de entwickelt "shariff" javascript-Erweiterung.

Jetzt habe ich aber das Problem, das beim Teilen der Url "http://www.trennwand-rink.com/datenschutz.php" auf Facebook weder das gewünschte Bild, noch der gewünschte Titel, bzw. die gewünschte Beschreibung erscheint. Stattdessen erscheinen die Metadaten der Starteseite "http://www.trennwand-rink.com".

Deshalb bin ich auf heise.de gegangen und habe dort eine Seitenlink auf Facebook geteilt. Das Ergebnis war das von heise gewünschte Bild, etc.....

Dann habe ich mir den Quelltext angeschaut und meine Metadaten entsprechend aufgebaut und trotzdem. Wenn man den Link auf Facebook teilt holt sich Facebook die Metadaten sonst wo her ....

Weiß bitte jemand Hilfe?

**Comment by criz** [comment]
Hi, kontrolliere Deine Metadaten mit dem Facebook Sharing Debugging Tool: https://developers.facebook.com/tools/debug/
Und "scrape" die Daten bei Bedarf erneut.

**Comment by Mausbiber** [comment]
thx
