### ISSUE TITLE
Tweaking the Source

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [heiseonline/shariff#189]
Question - I want to make a few tweaks. Namely I need to use `$(document).ready()` to trigger the JS because script nodes in the body are not allowed in my environment, and I also want to add a new attribute with a shortened URL for use in twitter.

I assume that after making those changes, I need to define the `SVERSION` environmental variable and then use `grunt` to re-create the files in the build directory? Basically what is in `release.sh` prior to the git commands?

I have not used grunt or nodejs before, getting from the src to the build is a bit of a mystery to me.

**Comment by AliceWonderMiscreations** [comment]
Oh yes I am aware many shortening services track users. We have our own that doesn't set any cookies.

**Comment by pmb0** [comment]
You may initialize Shariff in your `<head>` by using:

```html
<head>
[...]
<script>
$(document).ready(function() {
  $('.shariff').each(function() {
      if (!this.hasOwnProperty('shariff')) {
          this.shariff = new Shariff(this);
      }
  });
});
</script>
</head>
```
