### ISSUE TITLE
Provide a CSS without FontAwesome

### ISSUE THREAD

**Issue by tristanlins** [heiseonline/shariff#19]
I have already included FontAwesome in my layout from a local ressource. But the default `shariff.min.css` include FontAwesome once again from a global CDN... so FontAwesome will loaded twice!
I propose a `shariff.min.css` without FontAwesome and a `shariff.complete.css` including FontAwesome, similar to the js file.

**Comment by pmb0** [comment]
This should be fixed in Shariff@1.5.0, see https://github.com/heiseonline/shariff/commit/577441743b74a3846ddb190c872bf230cb14f417

**Comment by tristanlins** [comment]
:+1: nice, thanks :-)
