### ISSUE TITLE
Custom info link

### ISSUE THREAD

**Issue by phaleas** [heiseonline/shariff#196]
I'm currently working on (another) Shariff plugin for Wordpress, and I would like to give the option to use a custom info link via data-info-url. This works like charme, but the link always opens in a new window, which is ugly if you want an internal link. Linking to the Heise article is fine for Germans, but useless for most non Germans. So I guess I'd need something like 'data-info-target'.

Is there a way to prevent 'target="_blank"'

**Comment by compeak** [comment]
We would welcome a pull request introducing some sort of "custom link button".
