### ISSUE TITLE
Is there a way to know what user has clicked in the popup

### ISSUE THREAD

**Issue by ibes** [heiseonline/shariff#20]
Hi,

is there a way to know what the user has clicked in the popup. 
If he has pressed "like" or "cancel".

I would like to use this information to "fake update" the counter. 
If the user has liked the content, the counter could be increased by one go give him instand feedback. 
If the user canceled the context - nothing should happen.

Any other ideas for this suggestion?

**Comment by pmb0** [comment]
Hi,

[you cannot access  the popup from within your browser window](https://html.spec.whatwg.org/multipage/browsers.html#security-window).

The easiest way to do a "fake update" would be incrementing the counter every time someone closes a popup window. The "real" count could be updated periodically in the background. You could also time how long the popup window was displayed and guess whether the user clicked "cancel" based on that information. But that is rather crazy.
