### ISSUE TITLE
Remove bubbling of click events

### ISSUE THREAD

**Issue by goldquest** [heiseonline/shariff#200]
We tried to include shariff buttons into our sites, but unfortunately we rely on the twitter library to load twitter widgets.
The twitter library also sets a click handler to the document, which opens a popup for links with an intent URL. This leads to opening the sharing popup twice.
I know, that loading the twitter library bypasses the intent of shariff, but we don't want to include another twitter sharing button, if a twitter widget gets loaded.
I would suggest stopping the propagation of the event.
What's your opinion?

**Comment by Nebel54** [comment]
We had the same problem, I added a pull request here: #201

**Comment by compeak** [comment]
Closing because #201 was merged a while ago.
