### ISSUE TITLE
Official info site in english

### ISSUE THREAD

**Issue by geraldo** [heiseonline/shariff#207]
I remember a official translation of the article about Shariff at c't in English but actually only can find the [German version](https://www.heise.de/ct/artikel/Shariff-Social-Media-Buttons-mit-Datenschutz-2467514.html). Is there an English article for visitors (better from c't) which is not the technical description from Github?

**Comment by compeak** [comment]
Not at the moment. There may have been an article in English for our older "2 klick" project, but I'm unable to find it.
