### ISSUE TITLE
xing und Linkedin werden nicht gezählt

### ISSUE THREAD

**Issue by ThomasKujawa** [heiseonline/shariff#22]
wie auch bei einem anderen Tool werden die Zähler bei den xing und linkedin Button nicht korrekt angegeben.

Hier mein Fehlerbericht

https://github.com/macx/SocialMediaEnhancer/issues/47

**Comment by devimplode** [comment]
Ich glaube du bist im falschen repo gelandet. Es gibt den LinkedIn-Zähler im heiseonline/shariff-backend-php@master - Buttons gibt es aber noch keine :wink:

Dennoch zu deinem Problem:
Nicht reproduzierbar.
https://developer.linkedin.com/plugins/share-plugin-generator mit URL `http://www.familienfreund.de/`
https://www.linkedin.com/countserv/count/share?url=http://www.familienfreund.de/&lang=de_DE&format=json
Aktueller build von shariff-backend-php@ed2151c101154bacb37d41a4624cb21baf7ecd3d
Alle sagen: 45

Wenn es um erwähnte Seite geht, musst du wohl nur abwarten bis die Changes (die sind von heute morgen!) in dein WP-Plugin gemerged werden.

# TL;DR:
Auf Update waren!

**Comment by ThomasKujawa** [comment]
ich war wohl nur zu kurz.

Ich habe shariff via WP Plugin (https://wordpress.org/plugins/shariff/) eingebunden. Und die Fehlfunktion ist identisch mit der im SocialMediaEnhancer. Da ich die Fehlermeldung nicht noch einmal posten wollte, hatte ich nur den Link zum anderen Repo gepostet.

Entschuldigung!

Und Danke für den erläuternden Hinweis.
