### ISSUE TITLE
jQuery included twice (when using webpack) because of Shariff

### ISSUE THREAD

**Issue by PhilippSoehnlein** [heiseonline/shariff#222]
Just a small note, maybe someone will get into the same problem and find this solution here:

I build a website which generates a JavaScript bundle (which should include Shariff) with webpack. This website also has its own jQuery dependency. This leads to jQuery being included twice in the final bundle, when using Shariff 1.24.1 (it should be better with 1.25.1, which was unfortunately rejected). 
I think this happens because Shariff 1.24.1 defines jQuery as its own `dependency` instead of defining it as `peerDependency` in the `package.json`.

Not including jQuery twice can be fixed with the following setting in the `webpack.config.js`:
```js
module.exports = {
    // …
    resolve: {
        // …
        alias: {
            // fixate every jQuery requirement to our direct jQuery dependency. Shariff 1.24.1 brings its own jQuery and it would be included twice without this alias.
            'jquery': __dirname + '/node_modules/jquery/',
        },
    },
};
```

**Comment by njleonzhang** [comment]
@PhilippSoehnlein Tnx for this information. Have you researched further? Does this a Webpack bug or normal behavior to bundle a lib multi times?
