### ISSUE TITLE
Tag 1.25.0 and 1.25.1 releases

### ISSUE THREAD

**Issue by fantastic91** [heiseonline/shariff#225]
There seems to be https://github.com/heiseonline/shariff/commit/970895079470ce62d548410bac216999323513b2 and https://github.com/heiseonline/shariff/commit/861477a753769e1b4623abdd96ecbaec5bf63822 commits with messages about 1.25.0 and 1.25.1 releases but the actual release tags are missing.

Was it accidentally done or by intention?

**Comment by compeak** [comment]
This was accidental intention. I screwed up the releases and had to remove them.
