### ISSUE TITLE
Service: Flattr

### ISSUE THREAD

**Issue by ccoenen** [heiseonline/shariff#23]
Flattr seems like a match made in heaven for this.

**Comment by devimplode** [comment]
Is provided in request #21 
Also Pinterest and Reddit.

**Comment by malexmave** [comment]
Since #21 was not merged, what's the timeline (if any) for flattr support?

**Comment by devimplode** [comment]
Well, currently I have no time for this project - maybe in 2 months again.
Also an image replacement is needed for flattr.
Or:
- a new template system for supporting templates without any images - we need this anyway
- new image source - https://fonticons.com/ sounds promising

Or you simply merge my branch

**Comment by startef** [comment]
So any news about a Flattr integration? Really waiting for this.

**Comment by RockyTV** [comment]
I'm really waiting for this too, so I can completely remove my old flattr plugin.

**Comment by craiq** [comment]
http://craiq.github.io/shariff/

there you have it.
Just the icon is crappy, since it's not on font awesome

**Comment by nidico** [comment]
Looks like this has been implemented in #128.
