### ISSUE TITLE
Pinterest service never access og:image

### ISSUE THREAD

**Issue by 7oot** [heiseonline/shariff#230]
The problem is in the file `shariff/src/js/services/pinterest.js`

when no value or an empty string is provided through `data-media-url`, the meta ob:image is supposed to be used as a default.

However, control statement on line 12 is never true
```javascript
if (img && img.length <= 0) {
```
because an empty string is a boolean false, so the code block that pulls out the og:image is never executed.

The statement should be rewritten as follows
```javascript
if (!img || img.length <= 0) {
```

**Comment by liayn** [comment]
Sounds reasonable. Wanna push a PR?

**Comment by 7oot** [comment]
I just did :)
https://github.com/heiseonline/shariff/pull/231
