### ISSUE TITLE
Add required JQuery version to readme?

### ISSUE THREAD

**Issue by criz** [heiseonline/shariff#24]
Can you add a info somewhere in the readme about what jQuery Version is required by shariff?
In my experience it is jQuery 1.7 or higher.

**Comment by pmb0** [comment]
I don't know the exact required jQuery version. I think it is 1.7, too.

**Comment by campino2k** [comment]
https://github.com/heiseonline/shariff/blob/master/package.json#L41

**Comment by pmb0** [comment]
Shariff was developed with jquery@1.11. This is not the minimum required version to run Shariff.
