### ISSUE TITLE
tar and zip file 1.25.2 does include 1.25.1

### ISSUE THREAD

**Issue by Gregor-Agnes** [heiseonline/shariff#240]
When installing latest version with bower, you get the Source from the 1.25.1 version (which does not exist anymore). The source file of this (wrong) version are delivered in

https://github.com/heiseonline/shariff/archive/v1.25.2.tar.gz
and 
https://github.com/heiseonline/shariff/archive/v1.25.2.zip

The 1.25.1 version does not work in IE11

**Comment by liayn** [comment]
The actual issue is that the tag `v1.25.2` has been put on the wrong commit.
The actual release commit (which also contains the correct build data) is the subsequent commit.
So downloading the github archive for the tag delivers the sources of 1.25.2, but the build artifacts of 1.25.1

**Comment by thasmo** [comment]
@compeak Any chance this will be fixed soon so IE 11 will work properly? Thanks!

**Comment by pmb0** [comment]
> So downloading the github archive for the tag delivers the sources of 1.25.2, but the build artifacts of 1.25.1

We have this issue since our first release of Shariff. We will fix it soon by optimizing our release workflow.

**Comment by compeak** [comment]
This has been fixed for current releases.
