### ISSUE TITLE
Shariff renders the wrong buttons in Safari on Mac

### ISSUE THREAD

**Issue by thasmo** [heiseonline/shariff#243]
It either renders the wrong service-buttons or it doesn't render anything at all.

* Reproducible in the [demo](http://heiseonline.github.io/shariff/) on Safari 10 on Mac.
* In my case it doesn't render anything after a page refresh. (Initial request renders like in the demo.)

**Comment by pmb0** [comment]
I cannot reproduce on Safari 10.1/Mac.

**Comment by thasmo** [comment]
@pmb0 Does shariff support Safari 10.0/Mac? That's the version I use.

**Comment by thasmo** [comment]
@pmb0 Updated to Safari 10.1 - now it works. Feel free to close the issue if Safari 10.0 is not relevant/supported. Thanks for your help!
