### ISSUE TITLE
shariff.complete.js does not render buttons on Safari 10.1/Mac sporadically

### ISSUE THREAD

**Issue by thasmo** [heiseonline/shariff#245]
After resolving #243 I encountered shariff not rendering buttons sporadically after page load/refresh. This only seems to happen with `shariff.complete.js`. Using `shariff.min.js` it works in Safari 10.1/Mac, although it obviously breaks on IE.

**Comment by thasmo** [comment]
Nevermind, I didn't realize `shariff.complete.js` includes jQuery, which was the actual problem.

**Comment by pmb0** [comment]
`shariff.complete.js` includes a [custom polyfill](https://github.com/heiseonline/shariff/blob/master/src/js/dom.js) of jQuery. Its `document.ready` code was buggy and was improved in https://github.com/heiseonline/shariff/commit/1cf07921d54682f6de8a1d08aaeea67ba4ac2f57. This improvement will be part of our next release.
