### ISSUE TITLE
1.26.0 release does not follow semver

### ISSUE THREAD

**Issue by liayn** [heiseonline/shariff#246]
The build folder has been moved to dist, which is a major breaking change. This breaks automated scripts! Thus the version must be 2.0.0.

@pmb0 I suggest to:
- let a 2.0.0 follow immediately
- release a 1.27.0 which uses the old release scripts

**Comment by liayn** [comment]
Note: This is the second time such a mistake happens with Shariff. Please make sure Heise gets this straight for the future.

**Comment by pmb0** [comment]
Renaming `./dist` to `./build` and releasing 1.27.1 should fix this -- right?

**Comment by pmb0** [comment]
No, they are git-ignored now. I will publish a new release that contains `./build` soon. After that i will release 2.0.0.

**Comment by pmb0** [comment]
Is v1.26.1 fine for you?

**Comment by liayn** [comment]
Sure. As you like. Just make sure that people don't die if they update within v1. ;-)

**Comment by liayn** [comment]
Thanks for taking care quickly.
