### ISSUE TITLE
Extension for Pagekit CMS

### ISSUE THREAD

**Issue by SPQRInc** [heiseonline/shariff#247]
Hello,

I suggest to add my Pagekit extension `pagekit-sharrif` to the list of third-party integrations.

- GitHub: http://github.com/SPQRInc/pagekit-shariff
- Pagekit Marketplace: https://pagekit.com/marketplace/package/spqr/shariff
- Project page: https://spqr.wtf/projects/shariff

The extension is MIT licensed.

**Comment by liayn** [comment]
Create a pull request ;-)

**Comment by SPQRInc** [comment]
Alright - I did :)
