### ISSUE TITLE
jQuery error if backend returns null

### ISSUE THREAD

**Issue by mrcbnsls** [heiseonline/shariff#25]
With included PHP backend, the backend returns null if there are no shares for either of the passed services. In this case, I receive the following jQuery error in the console:

```javascript
TypeError: a is null
...rCase()},each:function(a,b,c){var d,e=0,f=a.length,g=r(a);if(c){if(g){for(;f>e;e...
```
The error points to f=a. I think the expected behavior would be to display "0" for each service instead of returning null.

**Comment by devimplode** [comment]
The backend only returns `null` if an error occurred.
So I think it's fine if jQuery fails in this case.

Please check your config if you specify the right domain.

**Comment by mrcbnsls** [comment]
Thanks, my fault.
