### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by bandanh** [heiseonline/shariff#251]
Hello all together,

I'm somehow a little bit confused. 

in the change log I found:

---
1.25.2 2017-06-13
- Restored the jQuery dependency for the min.js version. (liayn)

1.25.1 2017-04-21
- RELEASE reverted!
- Replaced jQuery with vanilla js. (glaszig)
---
There are 3 versions in `src/js/`
- shariff.complete.js -> jQuery includen
- shariff.js -> ??? No jQuery dependency?
- shariff.min.js -> jQuery dependency Restored

And if all Versions have some kind of jQuery dependency - when I go back to shariff 1.25.1, then I just get some Issues with IE 11? I could live with that :-D

**Comment by liayn** [comment]
Did you see that 1.26.2 has been released? 
As the readme (https://github.com/heiseonline/shariff#getting-started) clearly explains:

shariff.complete.js includes a small DOM library, so this one does not require any jQuery anymore (even though it can be present on the page, it does not hurt)

The shariff.min.js is intended for pages, where jQuery is present anyway, so shariff does not need to bring its DOM library along and the file is therefore smaller.
