### ISSUE TITLE
does not work in IE11

### ISSUE THREAD

**Issue by creatoras** [heiseonline/shariff#253]
For Version 1.26.1/2 i get an JS error "sign not allowed" and the buttons are not displayed.
I use the min-Version and own JQuery but it's the same with complete.

**Comment by liayn** [comment]
cannot confirm the issue. tried it on IE 11 with min-version and jquery loaded explicitly beforehand.

**Comment by liayn** [comment]
small correction: I do not get any JS error in the console, but the buttons are not rendered, because the `li` tags are not filled with the according CSS classes like `twitter`. So the buttons are all white, but they work on click.

**Comment by liayn** [comment]
jquery 3.1.1
shariff: 1.26.2

**Comment by creatoras** [comment]
Ok, than i have 2 problems.
First, the Sytsem is using JQuery 2.2.4 ... but i have only an error in IE 11.
The second are the Buttons. And i'm missing the special attributes in the li tags too.

**Comment by creatoras** [comment]
Replacing `.addClass(` with` .attr("class",` should fix the CSS-Bug.

**Comment by readme42** [comment]
```
$shareLink.prepend($('<span/>').addClass(`fa ${service.faName}`))
```

Uses the "new" multiline string format which is not supported by IE11 http://caniuse.com/#feat=template-literals

**Comment by xi** [comment]
- jQuery was replaced by custom code in #214
- #218 changed this so you could use either the build-in JS or jQuery
- the custom code does not work in IE11 (`classList.add()` only accepts a single parameter in IE). It seems like proper support was planned in #221 but was dropped for some reason.
- 9ee49c6e2cb76e1cb690897e98ed234cbd185d3e switched from browserify to webpack. This broke the "optional" part and now jquery is never used.

**Comment by cmb69** [comment]
> the custom code does not work in IE11 (classList.add() only accepts a single parameter in IE). 

Nor does [IE support the spread operator](https://kangax.github.io/compat-table/es6/).

**Comment by xi** [comment]
@cmb69 note that the code is transpiled to es5, so the spread operator is actually not an issue.

**Comment by cmb69** [comment]
@xi Ah, thanks. Missed that.

**Comment by liayn** [comment]
@compeak @pmb0 Would any of your maintainers please step in here and sort this out? A new release would be very appreciated!

**Comment by compeak** [comment]
This should be fixed in v2.x.

**Comment by udg-sabrina-nebauer** [comment]
Hi, 
this fix doesn't seem to work. The following function results in a syntax error in IE 11

names.split(' ').forEach(className => {
      this.classList.add(className)
    })

Is there a fix or workaround for that because this is supposed to be a fix for IE?

**Comment by novasneb** [comment]
Hi,
this fix doesn't seem to work. The following function results in a syntax error in IE 11

names.split(' ').forEach(className => {
this.classList.add(className)
})

Is there a fix or workaround for that because this is supposed to be a fix for IE?
Or is it possible to include the fix into an older version (jquery version) of the plugin?

**Comment by richard67** [comment]
@novasneb Maybe you should open a new issue. I am not sure if maintainers get notified about comments in closed issues.
