### ISSUE TITLE
IE10 Issues

### ISSUE THREAD

**Issue by ghost** [heiseonline/shariff#257]
In v1.25.2 the mail button is not displayed at all and the data-theme: grey is not working too. Tested on your demo page with Windows 7 and Internet Explorer 10:

http://heiseonline.github.io/shariff/

If I update shariff to v1.26.2 all the buttons are not displayed at all as mentioned here:

https://github.com/heiseonline/shariff/issues/253

**Comment by liayn** [comment]
Try v2.0.1

**Comment by pmb0** [comment]
It should be fixed in v2.x.

**Comment by compeak** [comment]
This should only happen when you try to load the demo page using the development server (`npm run dev`). Our GitHub hosted demo page has not been updated for a while now.

**Comment by compeak** [comment]
Does this problem occur when using [v2.0.4](https://github.com/heiseonline/shariff/releases/tag/2.0.4)?

Please do not use the demo page to verify.

**Comment by digitalgopnik** [comment]
I think this can be closed since IE 10 EOL is Jan 31, 2020.
