### ISSUE TITLE
Help with shariff

### ISSUE THREAD

**Issue by eugexx** [heiseonline/shariff#267]
I'm trying to use shariff for my personal web site. I'm started with the example code, but it doesn't work to me. 
My code is: 
![codice](https://user-images.githubusercontent.com/34278360/33615451-8253e646-d9da-11e7-8888-bc57ae598b57.png)

I don't see any button.  What i'm doing wrong?

**Comment by liayn** [comment]
Check the https://github.com/heiseonline/shariff/blob/develop/README.md file.
You miss the options on the `div` tag.

**Comment by eugexx** [comment]
i've seen that i've missed the jquery call. XD
However, is it possible to have round icon, or i only personalize with the 3 options called in readme.md?

**Comment by compeak** [comment]
> However, is it possible to have round icon

No.
