### ISSUE TITLE
Packaged versions of 1.26.2 do contain wrong build

### ISSUE THREAD

**Issue by derhasi** [heiseonline/shariff#273]
When using asset-packagist.org for downloading shariff in a composer project via `bower-asset/shariff` or `npm-asset/shariff`, the downloaded dist package cotnains code of `1.26.0` instead of `1.26.2`.

See https://asset-packagist.org/package/npm-asset/shariff and https://asset-packagist.org/package/bower-asset/shariff. The registries seem to refer to https://github.com/heiseonline/shariff/archive/1.26.2.tar.gz and https://github.com/heiseonline/shariff/archive/1.26.2.zip . Both of them hold the "old" code. 

But on the github release page https://github.com/heiseonline/shariff/releases/tag/1.26.2 two additional packages are listed as https://github.com/heiseonline/shariff/releases/download/1.26.2/shariff-1.26.2.tar.gz and https://github.com/heiseonline/shariff/releases/download/1.26.2/shariff-1.26.2.zip . Those packages hold the "new" code, but are not referenced in bower or npm.

## Workaround

1. Add the package definition to root composer.json manually:
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "bower-asset/shariff",
                "version": "1.26.2",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/heiseonline/shariff/releases/download/1.26.2/shariff-1.26.2.zip"
                },
                "type": "bower-asset",
                "license": [
                    "MIT"
                ]
            }
        },
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```
2. `composer remove bower-asset/shariff` and maybe all packages that depend on it.
3. `composer clear-cache`
4. `composer require bower-asset/shariff:1.26.2`

**Comment by compeak** [comment]
This should be fixed in the recent released.
