### ISSUE TITLE
shariff.complete.css does not link to fonts on CDN server anymore

### ISSUE THREAD

**Issue by martinburger** [heiseonline/shariff#278]
I just upgraded from version 1.23.0 to 2.0.4. I am using complete CSS file `shariff.complete.css` that contains all dependencies.

In version 1.23.0, that CSS file linked to font files on `netdna.bootstrapcdn.com`; for instance, `url(https://netdna.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.eot?v=4.5.0)`. In version 2.0.4, those links point to local files instead; for instance, `url(fontawesome-webfont.eot)`.

Is this change intended? With version 2.0.4, I have to host the font files myself.

**Comment by jamfx** [comment]
Hi,
I have the same Issue on the latest version of Sharrif in Joomla! Crazy thing:
In Firefox everything is shown properly. Chrome throws a warning...
In Console I got this error:
`Access to Font at 'https://mycloudfront-domain.cloudfront.net/templatesmytemplate/css/shariff/fa-brands-400.woff2' from origin 'https://www.mydomain.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mydomain.de' is therefore not allowed access.
somemoredomainstuff`
Any suggestions on this?
Any more info needed? 
Thanks for your help in Advance!
JamFX

**Comment by liayn** [comment]
The font files are included with the download package now.

The CORS thing has nothing to do with Shariff, your server setup prevents loading data from your CDN.
