### ISSUE TITLE
`dist` directory missing from npm packaged version 2.1.0

### ISSUE THREAD

**Issue by kleingeist** [heiseonline/shariff#280]
starting from version 2.1.0 the package from npm.js the package on npmjs [1] does not contain the `dist` directory with the already built javascript and css files anymore. this means we have to pull in the shariff requirements and your webpack config to be able to include shariff to our vendor.js via webpack.
i am not sure if this is the intended behavior, as #259 suggests the `dist` directory should be included in the package.

[1] https://registry.npmjs.org/shariff/-/shariff-2.1.0.tgz

**Comment by compeak** [comment]
This has been fixed with [v2.1.1](https://github.com/heiseonline/shariff/releases/tag/2.1.1).
