### ISSUE TITLE
"mail": Problems with Umlauts in field "Name des Absenders (optional)"

### ISSUE THREAD

**Issue by rhoellwarthwork** [heiseonline/shariff#288]
Hello,
Thank you for the software. It works fine for me (at heise.de), but ...
when I enter a name with umlauts in the field "Name des Absenders (optional)" I get the error message that there was something wrong but nothing tells me WHAT is wrong. After some try and error I found the umlauts in the name are the problem.

Please consider the following when improving/bugfixing the software:
* If they aren't supported it should be clearly marked
* If the user enters a umlaut the error message should tell the correct reason so that the user can correct it easily.

ronald

**Comment by compeak** [comment]
The problem you are describing is happening on the heise.de website. Please report it using the form [here](https://www.heise.de/kontakt/) (without using umlauts for now). This project has nothing to do with that form and does not track heise.de bugs.

**Comment by compeak** [comment]
I just realised you meant the "Diesen Beitrag per E-Mail versenden" form, not the "Kontakt" form. But the mail button provided by shariff just links to that form, so issues like this have to be submitted via the "Kontakt" form nonetheless and do not belong here.

**Comment by compeak** [comment]
I notified the appropriate persons about the problem.

**Comment by rhoellwarthwork** [comment]
Hello,
thanks for the quick response AND for the notification of the appropriate persons.
Awsome!
ronald
