### ISSUE TITLE
Possibility to add languages

### ISSUE THREAD

**Issue by theWeird** [heiseonline/shariff#29]
At the moment shariff supports only 3 languages: de, en, es

On multilingual sites you often have italian or french, maybe dutch or any other languages.

Please implement a possibility to add transations for all services without modifying the original min.js files.

Possibility 1: before using internal translation, check for a global hash variable like shariff_translations holding translations for all services.

Possibility 2: add a global accessible method to add more localisations by javascript during runtime.
The method could recieve two arguments like this: ('langcode', {googleplus: 'translation for googleplus'}

Possibility 3: add an optional data attribute like data-locale containing translations for all services in a hash. If given, ignore language settings and use the translations defined in data-locale.

Maybe there is a better solution than my 3. Would just be great to have a possibility to add more languages to shariff.

**Comment by mikejpr** [comment]
I agree with theWeird for his two statements: 
1. Possibility to add translation without modifying the core files.
2. We need more languages. 

I can contribute the following languages: french, italian and danish. 
What is the best way to submit them?

**Comment by pmb0** [comment]
This is how I would implement translation support:

```js
"use strict";

var Shariff = require("shariff");
new Shariff(myShariffElement, {
    l10nFile: "/path/to/fr-fr.json"

    // or:
    l10n: {
        key: "value"
    }
});
```

or as data attributes:

```html
<div class="shariff" data-l10n-file="/path/to/fr-fr.json">
<div class="shariff" data-l10n="{&quot;key&quot;:&quot;value&quot;}">
```

I do not know when there will be time to work on this feature so pull requests are welcome.

**Comment by mikejpr** [comment]
I add french, italian, danish and dutch translations.
I hope its okay like I submitted them, because I don't have much experience with GitHub.

**Comment by pmb0** [comment]
Thank you, i'm going to merge it. Btw, one pull request for all changes would have been okay. ;)

**Comment by rolandgeider** [comment]
I practically have no experience with i18n in javascript, but If you can, I suggest you take a look at [transifex](https://transifex.com/) (free for open source) and extract the strings to a format it understands. It makes it much easier for collaborators to submit translations, I have a little open source project myself and I'm constantly surprised how many people translate things.

**Comment by pmb0** [comment]
I just added the translations of @mikejpr -- thank you. I will work on the l10n feature as soon as i have time.

**Comment by jnachtigall** [comment]
+1 for transifex

**Comment by compeak** [comment]
A pull request introducing Transifex support would be most welcome.
