### ISSUE TITLE
Change reddit icon

### ISSUE THREAD

**Issue by koelling** [heiseonline/shariff#292]
I find the current reddit icon quite hard to recognize because of the circle in the background. At normal font size it looks like a laughing smiley or something. Would it be possible to change the icon to the `reddit-alien` icon from fontawesome?

https://fontawesome.com/icons/reddit-alien?style=brands

**Comment by richard67** [comment]
@koelling Pull request is #293 . Thanks for the hint.

**Comment by richard67** [comment]
@compeak Now as PR #293 is merged, can this issue here be closed? Or should it stay open until the change has been released? Or should we ask @koelling to close it after he has tested the PR after a new release?

**Comment by richard67** [comment]
@koelling Sorry, due to my mistake, the new reddit icon has been lost in the current Shariff release. I made a  new pull request #305 so it should be back in the next release.
