### ISSUE TITLE
How to add Flipboard sharing ?

### ISSUE THREAD

**Issue by studioart** [heiseonline/shariff#297]
How to add Flipboard sharing please?

https://about.flipboard.com/tools/

Thank you.

**Comment by richard67** [comment]
Am working on a pull request to implement that here so it will be in a future release.

**Comment by richard67** [comment]
@compeak Hmm, it seems fontawesome 4 does not support fa-flipboard. It seems it was added to fontawesome 5 only.
Maybe Shariff should update to fontawesome 5? But maybe that's not possible because version 5 is not on npm (yet).

**Comment by richard67** [comment]
@compeak I just found something about fontawesome 5 on npm. It seems they've changed name (no dash anymore) and splitted it into several packages (basic, brands, ...). So if Shariff shall stay with fontawesome (i.e. not change to other technologies) and support Flipboard, then Shariff needs to change from fontawesome 4 to fontawesome 5.

**Comment by richard67** [comment]
I have made 2 pull requests (PRs) to add the Flipboard service to Shariff:

1. PR #302 : This updates the Font Awesome web fonts to a newer version which provieds an icon for Flipboard.
2. PR #303 : This adds the new service.

Please test as described in the 2nd PR #303 , if possible (Linux host with git and npm installed is available), and let us know about the result in PR #303 with a comment.

**Comment by richard67** [comment]
Since PR #302 is merged, this issue can be closed.

**Comment by richard67** [comment]
Sorry, I meant #303

**Comment by compeak** [comment]
This has been implemented in v[3.0.0](https://github.com/heiseonline/shariff/releases/tag/3.0.0).
