### ISSUE TITLE
Problem with parameters in url

### ISSUE THREAD

**Issue by frankreckt** [heiseonline/shariff#30]
I have a problem setting the data-url to a url containing multiple parameters. 

My url a like this: http://myHost/index.php?page=einsatz_details&einsatz_id=2910

Setting this string to data-url, twitter and G+ are taking the whole url, facebook cuts it and only takes http://myHost/index.php?page=einsatz_details

Replacing the ampersand & with "& amp;" make facebook working, but breaks twitter and G+

Frank

**Comment by pmb0** [comment]
Hi @frankreckt , this should be fixed in v1.6.2.
