### ISSUE TITLE
Incompatible with bootstrap v. 4

### ISSUE THREAD

**Issue by karacho** [heiseonline/shariff#300]
Hi folks,
the col-statements in the .css and .js files do not work properly, if someone - like me - is using bootstrap 4. Therefore you can easily change the col-syntax (bootstrap 4 uses the same) to for example colSha- to work with bootstrap v 4 too.
Thanks

**Comment by flof** [comment]
Same problem here. I have defined 3 services, so shariff generates adds the class "col-3" to the container element, which results (bacause of bootstrap) in a column, that is so small, that the share buttons don't fit into.

As workaround, I added a couple of null's to the services-array:

`<div class="shariff" data-services="[&quot;twitter&quot;,&quot;facebook&quot;,&quot;googleplus&quot;,null,null,null]"></div>
`
This makes shariff add the class "col-6" to the container, which makes the container wide enough to fit the share buttons.

**Comment by richard67** [comment]
@karacho @flof Pull request (PR) to correct your issue is PR #304 . Can you test it as described in that PR and report back your test result there in a comment?

**Comment by richard67** [comment]
Since PR #304 is merged, this issue can be closed.

**Comment by compeak** [comment]
This should be fixed in v[3.0.0](https://github.com/heiseonline/shariff/releases/tag/3.0.0).
