### ISSUE TITLE
Share Article URL from main page

### ISSUE THREAD

**Issue by SebNik1** [heiseonline/shariff#308]
Hi folks, 

so far I failed to get two things fixed with myshariff on my site:

a) I can not share article links from the main page. I would like to share articles with their individual urls from the main page without opening each single site. It shows the buttons but it always shares the url of the frontpage. How can I replace the current command to get this working?
myshariff.php line 149: $articleurl = JURI::current();

b) I tried leaving out single articles by listing the IDs in the dedicated fields. But it does not work... 

I'd be really happy if someone could help. 

Thank you

**Comment by richard67** [comment]
Maybe it would be good sometimes to read documentation.

See here the description of the options: [https://github.com/heiseonline/shariff#options-data-attributes](https://github.com/heiseonline/shariff#options-data-attributes).

Check for option `data-url`.

And see here how to use the options: [https://github.com/heiseonline/shariff#getting-started](https://github.com/heiseonline/shariff#getting-started). Check the usage example.

**Comment by richard67** [comment]
P.S.: myshariff.php does not come from shariff. It could be a third party product which uses shariff, then you should ask them for help about their php file.

**Comment by SebNik1** [comment]
Thank you, I am using this on my joomla page... I read the documentation and I googled for 2 hours...

**Comment by SebNik1** [comment]
I will check for a certain myshariff page, thank you!

**Comment by richard67** [comment]
It could be MyShariff, a Joomla plugin:
[https://www.xadomir.de/webentwicklung/cms/joomla/plugins/17-myshariff-de.html](https://www.xadomir.de/webentwicklung/cms/joomla/plugins/17-myshariff-de.html).
You should check that, and if it is that plugin where myshariff.php comers from, you should ask them for support or post an issue there.
