### ISSUE TITLE
percent character in title

### ISSUE THREAD

**Issue by cryshell** [heiseonline/shariff#31]
A percent character in the title tag leads to a javascript error. demo page: http://demo.spectrattack.de/shariff/index.html

**Comment by pmb0** [comment]
Hi @cryshell, this issue was fixed in v1.6.1 (see #28). You're using v1.6.0.

**Comment by cryshell** [comment]
I followed the 'latest release' link today and downloaded https://github.com/heiseonline/shariff/archive/v1.6.1.zip - but the shariff.min.js included seems to be version 1.6.0.

**Comment by pmb0** [comment]
Ok, that seems to be a build process issue. Please use the files listed in https://github.com/heiseonline/shariff/tree/master/build
