### ISSUE TITLE
ICONs dont show up in Firefox if you use the easy frontend version

### ISSUE THREAD

**Issue by sotelgmbh** [heiseonline/shariff#313]
We did install the shariff.complete.css + shariff.complete.js and the buttons did show up.
But in FF you see no brand icon as FF has an issue loading external fonts.

Is there a workaround to upload the ICONs onto our own server and bind it direct!?

**Comment by richard67** [comment]
It is not enough just to upload shariff.complete.css + shariff.complete.js, you also have to upload the other files from the tar.gz or zip release package, i.e. you also need the font files.

**Comment by compeak** [comment]
The installation instructions were outdated. I tried to improve them in https://github.com/heiseonline/shariff/commit/098a685e2734e72983c071474c58ab67adbcb33c.
