### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by JoJoAction** [heiseonline/shariff#316]
We came across a secutity vulnerability:

If a web page, that includes Shariff, has the following title:

<title>You searched for &amp;lt;img src=a onerror=prompt(3);&amp;gt; - Google search</title>

Then that Code is executed, a prompt dialog appears - as many times as there are Shariff services implemented. If you for example implemented sharing via WhatsApp, Twitter and Google+, then the prompt arrears three times when opening the page. Same goes for:

<title>You searched for &lt;img src=a onerror=prompt(3);&gt; - Google search</title>

Which is also valid html.

Same also goes, if the attribute data-title is used instead:

[...] data-title="You searched for &amp;lt;img src=a onerror=prompt(3);&amp;gt; - Google search" [...]

And also here:

[...] data-title="You searched for &lt;img src=a onerror=prompt(3);&gt; - Google search" [...]

So this is especially relevant, when Shariff is included in a web page showing search results and having that search string in the web page title (which is and should be allowed behaviour, Google for example does so itself).

This is true for the current version, but also for older versions.

**Comment by liayn** [comment]
XSS this is called.

This line needs html escaping:
https://github.com/heiseonline/shariff/blob/develop/src/js/shariff.js#L201

**Comment by compeak** [comment]
> This line needs html escaping:
https://github.com/heiseonline/shariff/blob/develop/src/js/shariff.js#L201

@liayn Isn't it rather [line 158](https://github.com/heiseonline/shariff/blob/develop/src/js/shariff.js#L158)? This seems to fix it:

```
diff --git a/src/js/shariff.js b/src/js/shariff.js
index b2b96e7..84ac863 100644
--- a/src/js/shariff.js
+++ b/src/js/shariff.js
@@ -155,7 +155,7 @@ class Shariff {
     let title = this.getOption('title') || this.getMeta('DC.title')
     let creator = this.getMeta('DC.creator')
     if (title && creator) title = `${title} - ${creator}`
-    return title
+    return this._escapeHTML(title)
   }
 
   getReferrerTrack() {
@@ -170,6 +170,16 @@ class Shariff {
     return $.getJSON(url.format(baseUrl), callback)
   }
 
+  // see https://stackoverflow.com/q/6234773/5189715
+  _escapeHTML(unsafe) {
+    return unsafe
+      .replace(/&/g, "&amp;")
+      .replace(/</g, "&lt;")
+      .replace(/>/g, "&gt;")
+      .replace(/"/g, "&quot;")
+      .replace(/'/g, "&#039;")
+  }
+
   // add value of shares for each service
   _updateCounts(data, status, xhr) {
     if (!data) return
```

**Comment by liayn** [comment]
Disagree. Escaping always has to happen at the last point before the target protocol (HTML) is reached.
A call to getTitle must return the title "as is", it might be used somewhere else (not now, but future). I do not expect as developer to received a HTML escaped output from a normal getter.

That's why I proposed the escaping where the actual value is inserted into the DOM.

**Comment by compeak** [comment]
> Escaping always has to happen at the last point before the target protocol (HTML) is reached.

Agreed.

How about this:

1. Add

```
 getEscapedTitle() {
   return this._escapeHTML(this.getTitle)
 }

// see https://stackoverflow.com/q/6234773/5189715
_escapeHTML(unsafe) {
   return unsafe
     .replace(/&/g, "&amp;")
     .replace(/</g, "&lt;")
     .replace(/>/g, "&gt;")
     .replace(/"/g, "&quot;")
     .replace(/'/g, "&#039;")
 }
```
to `shariff.js`.

2. Have all services use `getEscapedTitle` to generate their share URLs.

**Comment by compeak** [comment]
Escaping `service.shareUrl` in

```js
var $shareLink = $('<a/>').attr('href', service.shareUrl)
```
doesn't seem to work.

Escaping only the title in the services does.

**Comment by liayn** [comment]
Hm... that's weird, I'll tests this myself too, because I'm curious.

**Comment by JoJoAction** [comment]
An alternate method to escape HTML would be:

function _escapeHTML(str) {
    var div=document.createElement('div');
    var node=document.createTextNode(str);
    div.appendChild(node);
    return div.innerHTML;
}

**Comment by liayn** [comment]
The actual (and only) culprit is twitter.js: `abbreviateText`
This piece does
```
  var div = document.createElement('div')
  div.innerHTML = text
```
That's where our title is interpreted as HTML.
