### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by arndf** [heiseonline/shariff#321]
Thanks for Shariff.
(I am not sure if this bug is the fault of Shariff itself or the WordPress plugin Shariff Wrapper)

There are numerous HTML errors caused by misplaced quotation marks. (Browsers swallow it anyway, but should be fixed.)

See topic over at WordPress: https://wordpress.org/support/topic/markup-errors/

Can somebody check this?

**Comment by liayn** [comment]
I can only speak for our TYPO3 integration, which is error free in this regard.

Without knowing any detail, I would assume that this happens with the service listing where a JSON array is improperly encoded as data attribute.
I would suggest moving this issue to the WordPress integration first and let the maintainers there check if they think they did everything right.

**Comment by startef** [comment]
Can be closed. Was a single typo in the WordPress plugin.
