### ISSUE TITLE
Is this DSGVO conform ?

### ISSUE THREAD

**Issue by LrMiLoef** [heiseonline/shariff#322]
I found this plugin on searching for an dsgvo conform solution of sharing buttons. Now i'm not shure if the usage of this plugin is legal. I thought it must have implemented an 2-Klick mechanism to be dsgvo conform 🤔

**Comment by compeak** [comment]
> I found this plugin

@LrMiLoef This is not a plugin. Maybe you were looking for the repository of one of [the third party integrations](https://github.com/heiseonline/shariff#third-party-integrations)?

> Now i'm not shure if the usage of this plugin is legal. I thought it must have implemented an 2-Klick mechanism to be dsgvo conform 🤔

Shariff does not load any resources from the services it implements without user interaction. If you want to know whether this satifies DSGVO requirements, you need to **ask a lawyer**.
