### ISSUE TITLE
class shariff-icon: svg's loaded via http instead of https

### ISSUE THREAD

**Issue by Yeru-314** [heiseonline/shariff#324]
Dear all,

many icons of the `class shariff-icon` of the social media platforms are loaded via the URL

http://www.w3.org/2000/svg

which also exists via https.
So my easy question is: Can future versions load this via https?
(Unfortunately, I have no shell access on my server to run a simple sed command myself.)

**Comment by startef** [comment]
Hi Yeru,

just speaking in general: http://www.w3.org/2000/svg is not an actual URL, it is just the namespace specification for a SVG element. So there is nothing being "loaded" by this and changing it to https would just make it an invalid namespace declaration.

Cheers
JP
