### ISSUE TITLE
Backend needed in any case?

### ISSUE THREAD

**Issue by nephilim75** [heiseonline/shariff#330]
Hej

do I need a phpbackend in any case?

Kind regards
//neph

**Comment by mb73** [comment]
You don’t need a backend at all if you don’t need to display the numbers …

**Comment by compeak** [comment]
> do I need a phpbackend in any case?

@nephilim75 Only if you want to display share counts.

> IMO these facts should be stated more clearly.

@mb73 The readme states that

> To enable the counters in the buttons, see section Backends.

and

> In order to display share counts with Shariff, you need the following backend:

I believe this to be rather clear, but you can suggest improvements by opening a pull request.
