### ISSUE TITLE
minds.com inclusion request

### ISSUE THREAD

**Issue by andysavage** [heiseonline/shariff#333]
Hello, I hope this is an appropriate place to ask.  Could you include minds.com - it's one of the best alternatives to facebook out there, and growing.
Thanks

**Comment by richard67** [comment]
Unfortunately there is no fontawesome icon for minds.com yet, see pull request [https://github.com/FortAwesome/Font-Awesome/issues/10183](https://github.com/FortAwesome/Font-Awesome/issues/10183), so it could be a problem to add it to Shariff with the right icon before FontAwesome have added it.

And I have not found any information yet e.g. on [https://github.com/bradvin/social-share-urls](https://github.com/bradvin/social-share-urls) about the sharing link.

@andysavage What kinds of social buttons do minds.com provide, and which one could be added to Shariff? Do you have any information about which would be the right link for sharing?

**Comment by andysavage** [comment]
richard67 sorry I missed the notification for your previous message. 

Yes That would do the job, or this is what they use on the site, but its an svg:
https://cdn-assets.minds.com/front/dist/assets/logos/bulb.svg

Whatever's easier. The main thing would be to have it available. Thanks a lot for replying.

**Comment by richard67** [comment]
Great, let's see what they answer.

**Comment by andysavage** [comment]
@richard67 Hi, they have not replied! I think just use the existing fontawesome lightbulb. Anyone using minds would know what that means, I think. I had a look at how to add to fontawesome but its beyond my level!

**Comment by richard67** [comment]
I still haven't found any information about any sharing buttons for minds.com for websites. So it seems their buttons only work within their own pages. @andysavage Have you ever seen any web page having a button for sharing on minds.com?

**Comment by andysavage** [comment]
@richard67 
> @andysavage Have you ever seen any web page having a button for sharing on minds.com?
Hi, no I have not. They don't seem to have anything about sharing other than sharing from minds to other social media. Perhaps the needed things don't even exist.

**Comment by NDdiet** [comment]
I have a button you can see at the bottom of any page or post such as [best Ozone generators]( https://nutritionaldiversity.com/ozone-therapy/)
we need an operable share link,  you will notice I am getting the refferal to the register page.
