### ISSUE TITLE
Social media icons are not displayed, instead "!" and "?"

### ISSUE THREAD

**Issue by Maqueez01** [heiseonline/shariff#334]
here a matching link:
https://legal-revolution.com/de/the-legal-revolutionary/jobs/legal-tech-jobangebot-001

it is  joomla 3.8. and i used the the newest plugin 2.5.2

**Comment by liayn** [comment]
@Maqueez01 Wrong project. Please ask the authors of your joomla plugin for help.

**Comment by Maqueez01** [comment]
ok
