### ISSUE TITLE
Fix LinkedIn Sharer-URL to 2020 Version

### ISSUE THREAD

**Issue by mpvesper** [heiseonline/shariff#378]
[shariff-linkedin-url.patch.txt](https://github.com/heiseonline/shariff/files/4918734/shariff-linkedin-url.patch.txt)

Please adjust the LinkedIn sharing URL.
Actually it is https://www.linkedin.com/shareArticle?url={url}&title={title}&summary={text}&source={provider}
2020 Version is: https://www.linkedin.com/sharing/share-offsite/?url={url}
Title, Summary and an Optional Image will be provided via. OpenGraph which is testable by the [Post Inspector](https://www.linkedin.com/post-inspector/).

I found solid information [here](https://github.com/bradvin/social-share-urls#linkedin).

**Comment by richard67** [comment]
Should be solved by PR #382 .
