### ISSUE TITLE
WhatsApp: Support for WhatsApp Web via wa.me (api.whatsapp.com)

### ISSUE THREAD

**Issue by NoNamePro0** [heiseonline/shariff#379]
**Currently the WhatsApp Link just shares to URL: `whatsapp://send?`.... which use the WhatsApp Mobile App. But don't WhatsApp Web, because it's a web site and not a app/program**

With the **Desktop App** _(WhatsApp Web Design as Program)_ have I no experience..

There is an alternative to use it for **WhatsApp Web** and **WhatsApp Mobile**: [`api.whatsapp.com`](https://api.whatsapp.com/send?text=&source=&data=&app_absent=) or [`wa.me`](https://wa.me/send?text=&source=&data=&app_absent=).

##### Mobile Only
- `whatsapp://send?text=A Text`

##### Web and Mobile
- `https://wa.me/send?text=A Text`
- `https://api.whatsapp.com/send?text=A Text`

## ToDO
- Just change in [`/src/js/services/whatsapp.js`](https://github.com/heiseonline/shariff/blob/develop/src/js/services/whatsapp.js#L67) from `whatsapp://` to `wa.me/`, i guess.

**Comment by richard67** [comment]
There is already a Pull Request for that, so no need to open a new issue. #366 .

**Comment by NoNamePro0** [comment]
Oh sorry. I don't saw it..
