### ISSUE TITLE
last release 18month ago: plz show life -and integrate some pull requests

### ISSUE THREAD

**Issue by hpvd** [heiseonline/shariff#387]
Would be awesome to show this great project is still alive and make a new release with integrating some of the available pull requests e.g. as a first step the ones already reviewed by @richard67
https://github.com/heiseonline/shariff/pull/382
https://github.com/heiseonline/shariff/pull/381

**Comment by NoNamePro0** [comment]
Yeah, that would really great!

**Comment by z1tr0t3c** [comment]
The project is still alive and I will look into it in a few days.

**Comment by richard67** [comment]
@z1tr0t3c Does this also apply to [shariff-backend-php](https://github.com/heiseonline/shariff-backend-php)?

**Comment by z1tr0t3c** [comment]
@richard67 Yes.

**Comment by hpvd** [comment]
awesome! Many thanks!
Looking forward this!

**Comment by hpvd** [comment]
@z1tr0t3c I hardly dare ask: is there any news on the subject?

**Comment by pbru87** [comment]
In case anyone stumbles upon this issue (as I did) and is looking for a newer version of Shariff, here you go: [download artifacts](https://gitlab.com/pbru/shariff/-/jobs/artifacts/pbru-branch/download?job=build).

I forked the current version (3.2.1), checked out a new branch from 'develop' and added the changes from [#381](https://github.com/heiseonline/shariff/pull/381) and [#382](https://github.com/heiseonline/shariff/pull/382). My fork can be found here: [https://gitlab.com/pbru/shariff](https://gitlab.com/pbru/shariff).

But I do hope to see upcoming releases from the original repository here. I look forward to it. (@z1tr0t3c )

@hpvd, @NoNamePro0: FYI

**Comment by hpvd** [comment]
@pbru87 many thanks for your work and letting us know!
Hopefully we can "re-split" / merge both again...
