### ISSUE TITLE
data-title

### ISSUE THREAD

**Issue by startef** [heiseonline/shariff#43]
Hello,

right now shariff uses the meta description to generate for example the tweet text and only uses the titel attribute as a fallback, if no meta description is found. Woulnd't it be more logical the other way around? Because when I provide the data-title attribute I most likely want shariff to use that and not ignore it for the sake of the meta describtion, otherwise I wouldn't bother to put it in, in the first place.

Or is there any other reason to ingore the data-title attribute?

startef

**Comment by pmb0** [comment]
Hi,

actually there is no `title` option support in Shariff, so it is ignored. The fallback uses the `<title>` tag of your document `<head>`. Do you need an own `title` option in Shariff?

**Comment by cooleisbaer** [comment]
I am planing an URL shorter like goo.gl od bit.ly just for German Market and  I need a data-title attribute to fetch and share the title from the shorten URL and not the title from the page itself.
Sample so far: http://sandbox.bd78.de/infinity-squared/index.php

**Comment by startef** [comment]
Oh yes, you are right. Somehow I thought there already was a title option. It would be useful for any kind of CMS, where you want share buttons on multiple posts / news / etc. on the same page. Especially blogs often rely on a main page including all posts (complete posts, not teasers) an have share buttons below every post.

**Comment by pmb0** [comment]
Hi, just added `data-title` support in https://github.com/heiseonline/shariff/commit/4b772fd65790bc86b9fb99abdf6adc9fe5a2bc97. Is this you are looking for? I would release it next week.

**Comment by cooleisbaer** [comment]
by the way?! Where can I post general issues and problems with shariff?!

**Comment by pmb0** [comment]
https://github.com/heiseonline/shariff/issues

**Comment by startef** [comment]
Thank you pmb0! I will test it tonight and let you know.

**Comment by startef** [comment]
So, testing is complete. Works very well. Thank you!

**Comment by pmb0** [comment]
Just released [v1.9.1](https://github.com/heiseonline/shariff/releases/tag/v1.9.1) which adds custom title support.
