### ISSUE TITLE
Change Twitter Icon

### ISSUE THREAD

**Issue by Sascha211** [heiseonline/shariff#437]
Hi,
can you please replace the Twitter button to reflect the change to "X"?

**Comment by Yavis** [comment]
And maybe additionally the url from twitter.com to x.com.

**Comment by michaelgack** [comment]
Is it planned to update the Twitter Icon and URL in the near future? We rely on this module and would like to keep using it. @bdeutsch-heise @StevenKowalzik

**Comment by richard67** [comment]
See #441 .
