### ISSUE TITLE
'latest release' downloads - files in build folder still on version 1.7.4

### ISSUE THREAD

**Issue by jdinse** [heiseonline/shariff#45]
Looks like the files in the build folder in https://github.com/heiseonline/shariff/releases/tag/v1.8.0 are still on version 1.7.4

**Comment by liayn** [comment]
The shariff.js indeed has a old header. The shariff.min.js seems ok

**Comment by jdinse** [comment]
No, you get me wrong. The files from master branch are ok. What I meant is the tagged version you can download as ZIP or TAR.GZ archive, which is "3 commits to master since this release" as github is telling me.

**Comment by compeak** [comment]
This should be fixed now (see [1.9.0](https://github.com/heiseonline/shariff/releases/tag/v1.9.0)).
