### ISSUE TITLE
use svgs for icons

### ISSUE THREAD

**Issue by Schweinepriester** [heiseonline/shariff#46]
title says all.

see <https://css-tricks.com/icon-fonts-vs-svg/>

**Comment by joomla-agency** [comment]
This can maybe reduce a big amount of not needed font awesome fluff?!

**Comment by craiq** [comment]
The Browser support is the problem:
"It all comes down to browser support. If you can go IE 9+ / Android 3+, inline SVG is better at pretty much everything than icon fonts. If you need the deeper browser support, I feel like an inline SVG fallback would be too big of a pain to be worth it (maintaining a PNG copy, inserting an additional element to display PNG version, hiding SVG element... it's weighty)."

IE8 is still common.

And the way it is, it's easier to implement with just one css and one js file.

The fluff in the CSS file can be cut out.
But then you can't use the other icons from the font with just set a class to an element anymore.
If you don't need this, you can take a look at my branch. (cut languages for now, more modules, new css) http://craiq.github.io/shariff/

**Comment by compeak** [comment]
As @craiq said:
> The Browser support is the problem

**Comment by mwld** [comment]
Coming back to this after two years. SVG icons are [now widely supported](https://caniuse.com/#feat=svg) and used. They also provide [better quality than an icon font](https://css-tricks.com/icon-fonts-vs-svg/).

You could use [Material Icons](https://materialdesignicons.com/) and bundle them directly with Shariff.

**Comment by flowtron** [comment]
FYI: [FontAwesome now also comes in an SVG-flavour](https://fontawesome.com/how-to-use/svg-with-js#how-it-works), which is also faster to render ;-)

**Comment by Schweinepriester** [comment]
I believe this issue is still/again relevant and should be reopened given https://caniuse.com/svg and the slow but sure death of IE11 ;)
