### ISSUE TITLE
shariff.min.js v1.8.0 

### ISSUE THREAD

**Issue by mkra** [heiseonline/shariff#47]
When i include the new shariff/build/shariff.min.js v1.8.0 i get two sharling list in my shariff container.

**Comment by pmb0** [comment]
Can you post a gist which reproduces the problem?

**Comment by mkra** [comment]
https://gist.github.com/mkra/b3ac8050009e5e0ad2b4#file-shariff-test-html
I used v1.9.1

**Comment by pmb0** [comment]
Shariff runs before `document.ready`, right after the `<script>`-tag. In your example it is initialized a second time, which results in two rows of buttons.

Starting from [1.9.2](https://github.com/heiseonline/shariff/releases/tag/v1.9.2) Shariff will make sure that the `<div>`-element does not have any children on initialization.

Additionally there is a `data`-attribute for setting the button orientation:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="shariff.complete.css">
</head>
<body>
    <div class="shariff" data-orientation="vertical"></div>

    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="shariff.min.js"></script>
</body>
</html>
```

Shariff is meant to be configured using the `data`-attributes. In most cases it is the easiest and fastest way to go.
