### ISSUE TITLE
http and https: protocol-free share counter?

### ISSUE THREAD

**Issue by wotis** [heiseonline/shariff#51]
Is it somehow possible, to count the share-values of a network regardlessly if the link is shared with http or https?
I have a website, that can be called with http and https. I noticed, that the share-values are different, when calling them with different protocols. It depends, if the link has been shared with or without https.
Is there a way to combine these two values into one link-count per button?

**Comment by pmb0** [comment]
Some (but not all) share services inspect your `link[rel="canonical"]` tag, if available. I think you should make sure that your content redirects to one canonical url and use this url with Shariff.
