### ISSUE TITLE
info button too wide for col-2 usage

### ISSUE THREAD

**Issue by orzechow** [heiseonline/shariff#53]
Using only one service plus the info button, causes the info button being `110px` wide (`108px` width + border):

    <div class="shariff" data-services="[&quot;facebook&quot;, &quot;info&quot;]" data-theme="grey">/div>

I didn't have this issue with shariff 1.7.1

**Comment by orzechow** [comment]
This issue is also happening with col-3 or col-1.

**Comment by ipa01** [comment]
thank you - I will fix this asap

**Comment by ipa01** [comment]
info button width is fixed in version 1.10.1
