### ISSUE TITLE
How to configure the mail button?

### ISSUE THREAD

**Issue by sirtet** [heiseonline/shariff#58]
i got shariff and the backend working, but the mail button initially did just open the page in a new tab, with `?view=mail` attached to the URL.
I expected it to work without config, as the other buttons.
I thought it would open a mail with a set subject, and the page URL in the body, like seen here:
http://granaton.com/shariff-social-sharing-wordpress/

With `data-mail-url="mailto:foo@example.com"`  added to the div, the mail program opens with a recipient set, but no other content...

Do i need to configure something else?

EDIT:
I was wondering what the idea behind the default value `?view=mail` for `data-mail-url` was.
Now i saw on heise online, that it's used there to bring up a webform to mail the article...
So, it DOES look like the mail button needs extra config.

**Comment by pmb0** [comment]
Just released v1.12.0. Now you are able to user `data-mail-subject` and `data-mail-body` to customize the mail. Defaults are current page's title (subject) and current page's url (body).

**Comment by Williwurstig** [comment]
`data-mail-subject` doesn't seem to work. Module uses always `data-title`.

**Comment by richard67** [comment]
@Williwurstig Note that according to the readme docs, `data-mail-subject` and `data-mail-body`are only used if the `data-mail-url` is a `mailto:` link, i.e. starts with `mailto:`. Is that the case in your situation?

**Comment by Williwurstig** [comment]
Yes, the mailto: is there, but empty: 
`<div class="myshariff" data-mail-body="Link: {url}" data-mail-subject="This is the subject" data-mail-url="mailto:">`
output:
`<a href="mailto:?subject=Pagetitle&amp;body=Link%3A%0Ahttp%3A%2F%2Ftestdomain.de" title="Per E-Mail versenden" role="button" aria-label="Per E-Mail versenden"><span class="fa fa-envelope"></span><span class="share_text">mail</span></a>`

Can anybody confirm this?

**Comment by richard67** [comment]
@Williwurstig I can confirm that. Can you open a new issue for this here? I think developers don't get notified about comments on closed issues.
