### ISSUE TITLE
Git Tags off by one version?

### ISSUE THREAD

**Issue by sirtet** [heiseonline/shariff#59]
If i browse here on github to eg. /build and select a tag, the version in the code is off by one version:

![shariff-tags](https://cloud.githubusercontent.com/assets/3509308/7534233/f4dda65a-f578-11e4-93ec-f684b4493bec.jpg)

Looks like a github problem at first, but i don't see that on other projects...

(I'm new to git/github, so it might be me misunderstanding...)

**Comment by pmb0** [comment]
The old build process was buggy and got fixed a while ago.

**Comment by sirtet** [comment]
Really?
![tags](https://cloud.githubusercontent.com/assets/3509308/7535091/b4eb4ada-f581-11e4-9684-ee79d72d4e26.jpg)
