### ISSUE TITLE
Mail-button default functionality broken

### ISSUE THREAD

**Issue by sirtet** [heiseonline/shariff#60]
A followup to #58, i found out that using version 1.4.7 DOES have a working mail-button out of the box.
It will open a new mail with the page-title as subject, and the URL in the Message.

Is this deprecated functionality, or is it a bug?

**Comment by pmb0** [comment]
You can use the mail service in two ways:

1. (Default) open current page with "?mail".
2. If you do not want to use this behaviour, you can set a custom "mailto:" link. You can customize mail subject and body in this case.

**Comment by sirtet** [comment]
Thanks, i see. I got it to work.

But the issue is still valid i think:
Mail works WITH some extra config, but not in the default state (just adding "mail" to the data-service attribute).

From a user view it would make more sense if the default was mailto:, as this could work immediately, versus the ?mail option, which needs an additional page before it works anyways.
