### ISSUE TITLE
Ideas for improved mail functionality

### ISSUE THREAD

**Issue by sirtet** [heiseonline/shariff#62]
In my opinion, a nice feature would be to also have a webform integrated. Something like addThis does:

![addthis-mail](https://cloud.githubusercontent.com/assets/3509308/7534684/1856e9e4-f57d-11e4-8d5a-138a1ffb6365.jpg)

Instead of (or in addition to) the webmail-links i'd add a "use your mail app" link, and i'd place this at the top, not bottom, as i think the own mail app is more user-friendly if you are on your own device. 
But for other cases the form would be a good addition.

The mail button is maybe a bit away from shariff's core functionality of being a privacy proxy, but i like it a lot, so i add my thoughts here as a reference and hope it's not seen as an abuse of the issue que.

PS:
Maybe also document the intended use of the default mail url parameter `?view=mail`

**Comment by compeak** [comment]
This is out of project scope because it would require adding mail functionality to the backend server.
