### ISSUE TITLE
Shariff not working w/o Backend?

### ISSUE THREAD

**Issue by CenkJaxon** [heiseonline/shariff#65]
Hi,
I try to use Shariff w/o Backend which works with `<div class="shariff clear"></div>`.
But as soon as I add the data-services tag to customize the buttons it disappears at the front-end. What might be the reason? Btw. I'm using shariff.min.js and shariff.complete.css.

**Comment by pmb0** [comment]
What exactly are you using as data-services value?

**Comment by CenkJaxon** [comment]
data-services="[&quot;facebook&quot;,&quot;twitter&quot;,&quot;googleplus&quot;,&quot;mail&quot;,&quot;info&quot;]"

**Comment by CenkJaxon** [comment]
```
data-services="[&quot;facebook&quot;,&quot;twitter&quot;,&quot;googleplus&quot;,&quot;mail&quot;,&quot;info&quot;]"

**Comment by pmb0** [comment]
This works for me:

```html
<div class="shariff" data-services="[&quot;facebook&quot;,&quot;twitter&quot;,&quot;googleplus&quot;,&quot;mail&quot;,&quot;info&quot;]"></div>
```

**Comment by CenkJaxon** [comment]
Still same. When I view the source-code, I can see the entities not printed as `&quot;` but as `"` for example. May this be the reason?

**Comment by CenkJaxon** [comment]
![2015-05-13 16_08_17-view-source_www zugeschnuert-shop de_gutscheintest](https://cloud.githubusercontent.com/assets/12429277/7612323/57077c60-f98a-11e4-9bd1-a393db9fd668.png)

**Comment by pmb0** [comment]
I assume the JS exception `Uncaught TypeError: undefined is not a function ` in `structured_autocomplete.js:496` causes JS execution to stop.

**Comment by pmb0** [comment]
No, I was wrong. I inspected your html markup. Your shariff element doesn't contain the data-services value as described above:

```html
<h4>Weitersagen</h4>
<div class="shariff" data-services="[\/facebook,twitter,googleplus,mail,info]"></div>
```

versus 

```html
<h4>Weitersagen</h4>
<div class="shariff" data-services="[&quot;facebook&quot;,&quot;twitter&quot;,&quot;googleplus&quot;,&quot;mail&quot;,&quot;info&quot;]"></div>
```

**Comment by CenkJaxon** [comment]
Yeah, like I asked before: You caught me trying to use escapes to get these entities work correctly. Somehow the template engine seems to interprete them :-/
![2015-05-13 16_32_12-remote desktop manager free plentymarkets](https://cloud.githubusercontent.com/assets/12429277/7612865/a9ced030-f98d-11e4-8243-d60e10609588.png)

**Comment by pmb0** [comment]
If you cannot fix this behavior, you can initialize Shariff in your own JS code.

HTML:
```js
var $shariff = $("<div>");
new Shariff($shariff, {services: ["twitter", "googleplus"]});
$shariff.appendTo("#share");
```

This code needs to run after your `<script src="shariff.min.js">` line.

**Comment by CenkJaxon** [comment]
This worked. Thanks a lot Philipp.

**Comment by pmb0** [comment]
👍

**Comment by liayn** [comment]
Don't know which template engine you're using, but with TYPO3 Fluid you have to use this syntax:
```
<rx:shariff data="{url: 'http://example.com/', services: '[\"whatsapp\",\"facebook\"]'}" />
```
(The example is using the viewhelper of the rx_shariff extension for TYPO3 CMS)

**Comment by CenkJaxon** [comment]
Thx. Didn't know there is an extension for typo3.

**Comment by liayn** [comment]
;-) Yep, comes with full shariff-backend integration.
http://typo3.org/extensions/repository/view/rx_shariff
