### ISSUE TITLE
Remove the protocol when querying the backend

### ISSUE THREAD

**Issue by tttp** [heiseonline/shariff#75]
On a site with both http and https, I have a backend (using the node version, proxied via nginx to handle the ssl and CORS enabled), and the queries are different:

from the https version:
https://backend.example.org/?url=https%3A%2F%2Fwww.example.org
from the http version:
https://backend.example.org/?url=http%3A%2F%2Fwww.example.org

and it returns different numbers for the http and the https option

However, if I manually change the url to 
https://backend.example.org/?url=www.example.org

I get the number I want, no matter if I query from the https or the http site.

Is there an option to not take into account the protocol ? Would it make more sense to modify the client to query without the http or https or change the backend server to remove the protocol?

**Comment by compeak** [comment]
Please use a [canonical-tag](https://en.wikipedia.org/wiki/Canonical_link_element) or define the url you want to be used with `data-url` (see [options](https://github.com/heiseonline/shariff#options-data-attributes)).

**Comment by tttp** [comment]
Thanks, I felt I was missing something
