### ISSUE TITLE
Shariff for Modx

### ISSUE THREAD

**Issue by MoonMaker** [heiseonline/shariff#77]
Hi, 

I developed the Modx Extra LudwigShariff that is using:
- Frontend: Latest build version of Shariff
- Backend: Shariff backend that is optimized for Modx

The resources:
- Description: https://ludwig.im/en/projects/ludwigshariff-shariff-for-modx
- Source Code: https://github.com/MoonMaker/modx/tree/master/Shariff
- Extra download: http://modx.com/extras/package/ludwigshariff

Cheers,

Thomas

**Comment by compeak** [comment]
Nice work. Please send a pull request if you want this added to our list of third party integrations.
