### ISSUE TITLE
add simple :hover effect for buttons

### ISSUE THREAD

**Issue by hallomatt** [heiseonline/shariff#80]
Hi there,

it would be nice to have a simple mouseover effect for :hover events, like so:

.shariff .facebook a {
    background-color: #3b5998
    transition: background-color 0.4s ease-in-out;
}

Makes the user experience much nicer ;)
Thx for the great work so far!

**Comment by OleAlbers** [comment]
why not just include this to your css yourself?

**Comment by hallomatt** [comment]
simple: it's a nice little enhancement to a modern user interface -
everyone should benefit from it ;)

**Comment by ipa01** [comment]
thank you, but we decided not to include transition effects
