### ISSUE TITLE
Shariff integration with Privacy Badger

### ISSUE THREAD

**Issue by SwartzCr** [heiseonline/shariff#81]
I work on an opensource browser add-on called Privacy Badger (https://github.com/EFForg/privacybadgerchrome) that is meant to protect users from online tracking. We currently have an aspect of it that is similar to shariff (https://github.com/EFForg/privacybadgerchrome/blob/master/src/socialwidgets.js). But in my opinion Shariff's solution seems nicer. I'm curious if someone from this project would be willing to contribute to Privacy Badger to add Shariff style widget blocking to Privacy Badger

**Comment by compeak** [comment]
Could you be more specific about what kind of contributions you would like (e.g. general info, code, ...)?

**Comment by compeak** [comment]
Please feel free to reopen this issue as soon as additional information can be supplied.
