### ISSUE TITLE
only german language works

### ISSUE THREAD

**Issue by skasberger** [heiseonline/shariff#83]
i tried to set the language used from "browser selected" to "english" and its still german. => teilen button for facebook. after this i also tried french, which also does not work. 

shariff Version 2.2.4
wordpress  4.2.2.

![teilen-bug](https://cloud.githubusercontent.com/assets/1374253/8024443/5b1ee03c-0d34-11e5-8d3c-d1df2d1f8a03.png)

**Comment by pmb0** [comment]
I guess you are using the "Shariff Wrapper" plugin for Wordpress? Please report this issue here: https://wordpress.org/support/plugin/shariff

In Shariff core there is no "browser selected" functionality.
