### ISSUE TITLE
[Feature Request] Service: Tumblr

### ISSUE THREAD

**Issue by Domochevsky** [heiseonline/shariff#94]
Can a share button for this service (tumblr) be added? Or are plans for adding it already in the making, for that matter.

**Comment by medienverbinder** [comment]
Hi,

I have built a first test for a tumblr share button without counter. 

Documentary to Tumblr ShareButton: https://www.tumblr.com/docs/de/share_button

Here the translated files to try Tumblr Share buttons: https://github.com/medienverbinder/shariff/tree/tumblr/build

![20150712_tumblr](https://cloud.githubusercontent.com/assets/4519686/8637584/3945624e-2899-11e5-9b67-c954d0eb4205.jpg)

I look forward to a feedback ;-)

**Comment by Domochevsky** [comment]
Impressive. Now how do I actually make use of these files... 
Do I simply override the contents of the dep folder with this? :)

**Comment by medienverbinder** [comment]
Hi !

Yes exactly. You need to override only the following files:

shariff.complete.css
shariff.complete.js
shariff.min.css
shariff.min.js

I have expands the existing sources with a Tumblr Share Button. The new available service name is "tumblr".

Please test beforehand necessarily in a development environment! ;-)

**Comment by Domochevsky** [comment]
Hum, did the test build disappear? I suddenly can't find it anymore.

**Comment by compeak** [comment]
@medienverbinder It would be really nice if you could send a pull request containing the tumblr button.

**Comment by medienverbinder** [comment]
Added simple tumblr support with modified demo page and send a pull request containing the tumblr button.

**Comment by compeak** [comment]
#121 has been merged.
