### ISSUE TITLE
Issue with language codes

### ISSUE THREAD

**Issue by McAtze** [heiseonline/shariff#97]
There're some lang codes which are not clearly what country is it. Are this ISO 3166 lang codes (https://en.wikipedia.org/wiki/ISO_3166-1)?

ja (??), ko (??), sl (sierra leone ??), sr (suriname ??), sv (el salvador ??) and zh (??)

Thanks for helping.

**Comment by craiq** [comment]
you can check the code, eg https://github.com/heiseonline/shariff/blob/master/src/js/services/facebook.js

and then use https://translate.google.com/ with language recognition

ja = japan, ko = korean, sl = slovenian, ...

**Comment by heppstux** [comment]
Hello @McAtze,

at least in my understanding, translations should follow iso-639-1's two-letter-codes (compare https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

If you find translations in shariff not respecting this standard let us know!

Thanks in advance

**Comment by compeak** [comment]
This question seems to be answered. Feel free to reopen.
