### ISSUE TITLE
Don't show '<' and '>' around a linked shared by email

### ISSUE THREAD

**Issue by Twiek** [heiseonline/shariff#98]
You can see it on your demo page:

![bildschirmfoto 2015-07-17 um 13 47 28](https://cloud.githubusercontent.com/assets/432388/8746534/7dba1a38-2c8a-11e5-8bbe-d52ec0d4f3f0.png)

If I click the email button I get

![bildschirmfoto 2015-07-17 um 13 47 47](https://cloud.githubusercontent.com/assets/432388/8746540/89dd22e2-2c8a-11e5-99a8-4d659259d337.png)

Instead of '`<http://www.heise.de/>`' I would like to see just '`http://www.heise.de/`'

**Comment by craiq** [comment]
it's added on purpose. So there might be a reason for this.

You can check with my build, if there are error's: 
https://github.com/craiq/shariff/tree/Craiq/FB-like

but I need to warn you, my build uses completely new css
the demo might be enough to test
http://craiq.github.io/shariff/

**Comment by sehkunde** [comment]
Hi,

some mail clients line wrap long urls and break them. Wrapping them in angle brackets can help. See this recommendation: http://www.w3.org/Addressing/URL/5.1_Wrappers.html

You should be able to suppress the brackets by passing a modified function for the property "mailBody". This is the default function:

    mailBody: function() { return '<' + this.getURL() + '>'; },

I hope that answers your question.
